import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import type { ClientSession } from 'mongoose';
import type { AuthUser } from '../common/auth-user.js';
import { OperationalStore } from '../common/operational-store.js';
import { civilDate } from '../contracts/contracts.rules.js';
import { PROJECT_MODELS } from './projects.schemas.js';
import { timeMinutes, validateDependencies } from './projects.rules.js';
import * as D from './projects.dto.js';
const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
@Injectable()
export class ProjectsService {
 constructor(private store:OperationalStore){}
 private model(name:string){return this.store.model(name);}
 private write<T>(u:AuthUser,p:string,event:string,fn:(a:AuthUser,s:ClientSession)=>Promise<T>){return this.store.write(u,p,event,PROJECT_MODELS,fn);}
 private clean(row:any,a:AuthUser){const {inputHash,requestId,...r}=row.toObject?row.toObject():row;if(r.revisions&&!a.permissions?.includes('projetos.custos'))r.revisions=r.revisions.map(({budgetCents,...revision}:any)=>revision);return r;}
 private scope(a:AuthUser){return {tenantId:a.tenantId,...(a.permissions?.includes('projetos.equipe')?{}:{memberIds:a.sub})};}
 private async project(a:AuthUser,id:string,s?:ClientSession){const p=await this.model('BusinessProject').findOne({_id:this.store.id(id),...this.scope(a)}).session(s??null);if(!p)throw new NotFoundException('Projeto não encontrado.');return p;}
 private version(row:any,n:number){if(row.version!==n)throw new ConflictException('Registro atualizado. Recarregue a tela.');}
 private date(d:string){try{return civilDate(d);}catch{throw new BadRequestException('Data inválida.');}}
 private async users(a:AuthUser,ids:string[],s:ClientSession){if(await this.model('User').countDocuments({_id:{$in:ids},tenantId:a.tenantId,status:'ACTIVE',active:true}).session(s)!==ids.length)throw new BadRequestException('Equipe contém pessoa indisponível nesta empresa.');}
 private async task(a:AuthUser,id:string,s?:ClientSession){const t=await this.model('ProjectTask').findOne({_id:this.store.id(id),tenantId:a.tenantId}).session(s??null);if(!t)throw new NotFoundException('Tarefa não encontrada.');const p=await this.project(a,String(t.projectId),s);return {t,p};}
 private editable(p:any){if(!['PLANNED','ACTIVE'].includes(p.status))throw new ConflictException('Projeto não permite alterações neste estado.');}
 async people(u:AuthUser,q:D.ProjectQuery){const a=await this.store.access.require(u,['projetos.visualizar']);return this.store.page('User',{tenantId:a.tenantId,status:'ACTIVE',active:true,...(q.search?{name:new RegExp(escape(q.search),'i')}:{})},q,{name:1,_id:1},'_id name');}
 async list(u:AuthUser,q:D.ProjectQuery){const a=await this.store.access.require(u,['projetos.visualizar']);const page=await this.store.page('BusinessProject',{...this.scope(a),...(q.status?{status:q.status}:{}),...(q.search?{name:new RegExp(escape(q.search),'i')}:{})},q);return {...page,items:page.items.map(r=>this.clean(r,a))};}
 async detail(u:AuthUser,id:string){const a=await this.store.access.require(u,['projetos.visualizar']),p=await this.project(a,id);const tasks=await this.model('ProjectTask').aggregate([{$match:{tenantId:this.store.id(a.tenantId!),projectId:p._id}},{$group:{_id:'$status',count:{$sum:1},estimatedMinutes:{$sum:'$estimatedMinutes'}}}]);const times=await this.model('ProjectTime').aggregate([{$match:{tenantId:this.store.id(a.tenantId!),projectId:p._id,...(a.permissions?.includes('projetos.aprovar_horas')?{}:{actorId:this.store.id(a.sub)})}},{$group:{_id:{status:'$status',billable:'$billable'},minutes:{$sum:'$minutes'}}}]);return {...this.clean(p,a),tasks,times,timeScope:a.permissions?.includes('projetos.aprovar_horas')?'PROJECT':'OWN'};}
 async create(u:AuthUser,d:D.ProjectDto){this.date(d.startsOn);this.date(d.endsOn);if(d.endsOn<d.startsOn)throw new BadRequestException('Prazo anterior ao início.');return this.write(u,'projetos.criar','projects.created',async(a,s)=>{
  await this.store.access.require(a,['projetos.custos'],s);const previous=await this.store.replay('BusinessProject',a,d,s);if(previous){await this.project(a,String(previous._id),s);return this.clean(previous,a);}
  const memberIds=[...new Set([...d.memberIds,d.managerId,a.sub])];await this.users(a,memberIds,s);let party:any;if(d.partyId){party=await this.model('BusinessParty').findOne({_id:d.partyId,tenantId:a.tenantId,active:true,roles:'CUSTOMER'}).session(s);if(!party)throw new BadRequestException('Cliente indisponível.');}
  const {scope,endsOn,budgetCents,...data}=d;const [p]=await this.model('BusinessProject').create([{...data,...this.store.fields(a,d),memberIds,partyName:party?.name,revisions:[{scope,endsOn,budgetCents,revision:1,actorId:a.sub,at:new Date(),reason:'Escopo inicial'}],history:[{status:'PLANNED',reason:'Projeto criado',actorId:a.sub,at:new Date()}]}],{session:s});return this.clean(p,a);
 });}
 async state(u:AuthUser,id:string,d:D.ProjectStateDto){return this.write(u,'projetos.gerenciar','projects.status.changed',async(a,s)=>{const p=await this.project(a,id,s);this.version(p,d.version);const states:Record<string,string[]>={PLANNED:['ACTIVE','CANCELED'],ACTIVE:['SUSPENDED','COMPLETED','CANCELED'],SUSPENDED:['ACTIVE','CANCELED'],COMPLETED:['ACTIVE']};if(!states[p.status]?.includes(d.status))throw new ConflictException('Transição inválida.');if(d.status==='COMPLETED'&&await this.model('ProjectTask').exists({tenantId:a.tenantId,projectId:p._id,status:{$nin:['DONE','CANCELED']}}).session(s))throw new ConflictException('Conclua ou cancele as tarefas pendentes.');p.status=d.status;p.version++;p.history.push({status:d.status,reason:d.reason,actorId:a.sub,at:new Date()});await p.save({session:s});return this.clean(p,a);});}
 async revise(u:AuthUser,id:string,d:D.ProjectRevisionDto){this.date(d.endsOn);return this.write(u,'projetos.gerenciar','projects.scope.revised',async(a,s)=>{await this.store.access.require(a,['projetos.custos'],s);const p=await this.project(a,id,s);this.version(p,d.version);this.editable(p);if(d.endsOn<p.startsOn)throw new BadRequestException('Prazo anterior ao início.');if(await this.model('ProjectTask').exists({tenantId:a.tenantId,projectId:p._id,status:{$nin:['DONE','CANCELED']},dueOn:{$gt:d.endsOn}}).session(s))throw new ConflictException('Há tarefas previstas após o novo prazo.');const {version,...revision}=d;p.revisions.push({...revision,revision:p.revisions.length+1,actorId:a.sub,at:new Date()});p.version++;await p.save({session:s});return this.clean(p,a);});}
 async tasks(u:AuthUser,q:D.ProjectQuery){const a=await this.store.access.require(u,['projetos.visualizar']);if(!q.projectId)throw new BadRequestException('Selecione o projeto.');await this.project(a,q.projectId);return this.store.page('ProjectTask',{tenantId:a.tenantId,projectId:q.projectId,...(q.search?{title:new RegExp(escape(q.search),'i')}:{})},q,{dueOn:1,_id:1});}
 private async dependencies(a:AuthUser,projectId:any,id:string,dependencies:string[],s:ClientSession){const tasks=await this.model('ProjectTask').find({tenantId:a.tenantId,projectId}).select('_id dependencies').session(s).lean();if(tasks.length>=1000&&!tasks.some(t=>String(t._id)===id))throw new ConflictException('Limite de mil tarefas por projeto atingido.');try{validateDependencies(tasks.map((t:any)=>({id:String(t._id),dependencies:t.dependencies.map(String)})),id,dependencies);}catch(e){throw new BadRequestException((e as Error).message);}}
 async createTask(u:AuthUser,d:D.ProjectTaskDto){this.date(d.dueOn);return this.write(u,'projetos.planejar','projects.task.created',async(a,s)=>{const p=await this.project(a,d.projectId,s);this.editable(p);const previous=await this.store.replay('ProjectTask',a,d,s);if(previous)return this.clean(previous,a);if(!p.memberIds.some((i:any)=>String(i)===d.assignedId))throw new BadRequestException('Responsável precisa participar da equipe.');await this.users(a,[d.assignedId],s);if(d.dueOn<p.startsOn||d.dueOn>p.revisions.at(-1).endsOn)throw new BadRequestException('Prazo fora da vigência do projeto.');const id=new this.store.db.base.Types.ObjectId();await this.dependencies(a,p._id,String(id),d.dependencies,s);const [t]=await this.model('ProjectTask').create([{...d,...this.store.fields(a,d),_id:id}],{session:s});return this.clean(t,a);});}
 async taskDependencies(u:AuthUser,id:string,d:D.TaskDependenciesDto){return this.write(u,'projetos.planejar','projects.dependencies.changed',async(a,s)=>{const {t,p}=await this.task(a,id,s);this.editable(p);this.version(t,d.version);if(t.status!=='TODO')throw new ConflictException('Dependências só podem mudar antes da execução.');await this.dependencies(a,p._id,id,d.dependencies,s);t.dependencies=d.dependencies;t.version++;await t.save({session:s});return this.clean(t,a);});}
 async taskState(u:AuthUser,id:string,d:D.TaskStateDto){return this.write(u,'projetos.executar','projects.task.changed',async(a,s)=>{const {t,p}=await this.task(a,id,s);this.editable(p);this.version(t,d.version);if(String(t.assignedId)!==a.sub&&!a.permissions?.includes('projetos.gerenciar'))throw new ForbiddenException('Tarefa atribuída a outro colaborador.');if(['DONE','CANCELED'].includes(d.status)||['DONE','CANCELED'].includes(t.status))await this.store.access.require(a,['projetos.gerenciar'],s);const states:Record<string,string[]>={TODO:['IN_PROGRESS','CANCELED'],IN_PROGRESS:['REVIEW','TODO','CANCELED'],REVIEW:['DONE','IN_PROGRESS','CANCELED'],DONE:['TODO'],CANCELED:['TODO']};if(!states[t.status]?.includes(d.status))throw new ConflictException('Transição inválida.');if(['IN_PROGRESS','REVIEW','DONE'].includes(d.status)&&await this.model('ProjectTask').exists({tenantId:a.tenantId,projectId:p._id,_id:{$in:t.dependencies},status:{$ne:'DONE'}}).session(s))throw new ConflictException('Conclua as dependências primeiro.');if(['DONE','CANCELED'].includes(t.status)&&await this.model('ProjectTask').exists({tenantId:a.tenantId,projectId:p._id,dependencies:t._id,status:{$nin:['TODO','CANCELED']}}).session(s))throw new ConflictException('Há tarefas dependentes já iniciadas; trate-as antes de reabrir.');t.status=d.status;t.version++;t.history.push({status:d.status,reason:d.reason,actorId:a.sub,at:new Date()});await t.save({session:s});return this.clean(t,a);});}
 async comments(u:AuthUser,id:string,q:D.ProjectQuery){const a=await this.store.access.require(u,['projetos.visualizar']);await this.task(a,id);return this.store.page('ProjectComment',{tenantId:a.tenantId,taskId:id},q);}
 async comment(u:AuthUser,id:string,d:D.TaskCommentDto){return this.write(u,'projetos.executar','projects.comment.created',async(a,s)=>{const {t,p}=await this.task(a,id,s);this.editable(p);const payload={...d,taskId:id},previous=await this.store.replay('ProjectComment',a,payload,s);if(previous)return this.clean(previous,a);const [c]=await this.model('ProjectComment').create([{...this.store.fields(a,payload),projectId:p._id,taskId:t._id,text:d.text,authorName:a.name}],{session:s});return this.clean(c,a);});}
 async times(u:AuthUser,q:D.ProjectQuery){const a=await this.store.access.require(u,['projetos.visualizar']);if(!q.projectId)throw new BadRequestException('Selecione o projeto.');await this.project(a,q.projectId);return this.store.page('ProjectTime',{tenantId:a.tenantId,projectId:q.projectId,...(a.permissions?.includes('projetos.aprovar_horas')?{}:{actorId:a.sub})},q);}
 async time(u:AuthUser,d:D.ProjectTimeDto){let minutes:number;try{minutes=timeMinutes(d.startsAt,d.endsAt);}catch(e){throw new BadRequestException((e as Error).message);}return this.write(u,'projetos.horas','projects.time.recorded',async(a,s)=>{const {t,p}=await this.task(a,d.taskId,s);this.editable(p);if(!p.memberIds.some((i:any)=>String(i)===a.sub))throw new ForbiddenException('Apontamento exige participação na equipe.');const previous=await this.store.replay('ProjectTime',a,d,s);if(previous)return this.clean(previous,a);const startsAt=new Date(d.startsAt),endsAt=new Date(d.endsAt);if(await this.model('ProjectTime').exists({tenantId:a.tenantId,actorId:a.sub,status:{$ne:'REJECTED'},startsAt:{$lt:endsAt},endsAt:{$gt:startsAt}}).session(s))throw new ConflictException('Já há um apontamento nesse intervalo.');const [r]=await this.model('ProjectTime').create([{...d,...this.store.fields(a,d),projectId:p._id,startsAt,endsAt,minutes}],{session:s});return this.clean(r,a);});}
 async approveTime(u:AuthUser,id:string,d:D.TimeApprovalDto){return this.write(u,'projetos.aprovar_horas','projects.time.reviewed',async(a,s)=>{const t=await this.model('ProjectTime').findOne({_id:this.store.id(id),tenantId:a.tenantId}).session(s);if(!t)throw new NotFoundException('Apontamento não encontrado.');await this.project(a,String(t.projectId),s);this.version(t,d.version);if(t.status!=='PENDING')throw new ConflictException('Apontamento já analisado.');t.status=d.status;t.reason=d.reason;t.reviewerId=a.sub;t.reviewedAt=new Date();t.version++;await t.save({session:s});return this.clean(t,a);});}
}
