import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import type { ClientSession } from 'mongoose';
import type { AuthUser } from '../common/auth-user.js';
import { OperationalStore } from '../common/operational-store.js';
import { civilDate } from '../contracts/contracts.rules.js';
import { csvCell } from '../finance/fiscal-sales.service.js';
import { OWNERS } from '../tenants/tenant-access.service.js';
import { BI_MODELS } from './bi.schemas.js';
import * as D from './bi.dto.js';
const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
@Injectable()
export class BiService {
 constructor(private store:OperationalStore){}
 private model(name:string){return this.store.model(name);}
 private clean(row:any){const {inputHash,requestId,...r}=row.toObject?row.toObject():row;return r;}
 private write<T>(u:AuthUser,p:string,event:string,fn:(a:AuthUser,s:ClientSession)=>Promise<T>){return this.store.write(u,p,event,BI_MODELS,fn);}
 private scope(a:AuthUser){return {tenantId:a.tenantId,...(a.permissions?.includes('bi.equipe')?{}:{allowedUserIds:a.sub})};}
 private async dataset(a:AuthUser,id:string,s?:ClientSession){const r=await this.model('BiDataset').findOne({_id:this.store.id(id),...this.scope(a)}).session(s??null);if(!r)throw new NotFoundException('Fonte de dados não encontrada.');return r;}
 private date(value:string){try{return civilDate(value);}catch{throw new BadRequestException('Data civil inválida.');}}
 private period(q:D.BiQuery){const month=q.month??new Date().toISOString().slice(0,7),from=this.date(q.from??month+'-01'),date=new Date(month+'-01T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);const to=this.date(q.to??date.toISOString().slice(0,10));if(to<from||(Date.parse(to)-Date.parse(from))/86400000>366)throw new BadRequestException('Selecione um período de até 367 dias.');return {from,to};}
 private async users(a:AuthUser,ids:string[],s:ClientSession){if(await this.model('User').countDocuments({_id:{$in:ids},tenantId:a.tenantId,status:'ACTIVE',active:true}).session(s)!==ids.length)throw new BadRequestException('Pessoa indisponível nesta empresa.');}
 async people(u:AuthUser,q:D.BiQuery){const a=await this.store.access.require(u,['bi.visualizar']);if(!a.permissions?.some(p=>['bi.configurar','bi.compartilhar'].includes(p)))throw new ForbiddenException('Sem permissão para configurar compartilhamentos.');return this.store.page('User',{tenantId:a.tenantId,status:'ACTIVE',active:true},q,{name:1,_id:1},'_id name');}
 async list(u:AuthUser,q:D.BiQuery){const a=await this.store.access.require(u,['bi.visualizar']);return this.store.page('BiDataset',{...this.scope(a),...(q.search?{name:new RegExp(escape(q.search),'i')}:{})},q);}
 async create(u:AuthUser,d:D.DatasetDto){return this.write(u,'bi.configurar','bi.dataset.created',async(a,s)=>{const previous=await this.store.replay('BiDataset',a,d,s);if(previous){await this.dataset(a,String(previous._id),s);return this.clean(previous);}const ids=[...new Set([...d.allowedUserIds,a.sub])];await this.users(a,ids,s);const [r]=await this.model('BiDataset').create([{...d,...this.store.fields(a,d),allowedUserIds:ids}],{session:s});return this.clean(r);});}
 async share(u:AuthUser,id:string,d:D.BiShareDto){return this.write(u,'bi.compartilhar','bi.dataset.shared',async(a,s)=>{const r=await this.dataset(a,id,s);if(r.version!==d.version)throw new ConflictException('Fonte atualizada.');await this.users(a,d.allowedUserIds,s);r.allowedUserIds=d.allowedUserIds;r.version++;r.accessHistory.push({actorId:a.sub,at:new Date(),reason:d.reason,allowedUserIds:d.allowedUserIds});await r.save({session:s});return this.clean(r);});}
 async import(u:AuthUser,id:string,d:D.BiImportDto){if(new Set(d.rows.map(r=>r.key)).size!==d.rows.length)throw new BadRequestException('Chaves repetidas no arquivo.');d.rows.forEach(r=>this.date(r.date));return this.write(u,'bi.importar','bi.data.imported',async(a,s)=>{
  const dataset=await this.dataset(a,id,s),payload={...d,datasetId:id};const previous=await this.store.replay('BiImport',a,payload,s);if(previous)return {_id:previous._id,inserted:previous.inserted,repeated:previous.repeated};const importId=new this.store.db.base.Types.ObjectId();let inserted=0,repeated=0;
  for(const row of d.rows){const normalized={...row,category:row.category.trim()},fingerprint=this.store.hash(normalized);const existing=await this.model('BiRecord').findOne({tenantId:a.tenantId,datasetId:id,key:row.key}).session(s);if(existing){if(existing.fingerprint!==fingerprint)throw new ConflictException(`Chave ${row.key} já tem outro conteúdo. A importação inteira foi recusada.`);repeated++;continue;}await this.model('BiRecord').create([{...normalized,tenantId:a.tenantId,datasetId:id,importId,actorId:a.sub,fingerprint}],{session:s});inserted++;}
  const [batch]=await this.model('BiImport').create([{...this.store.fields(a,payload),_id:importId,datasetId:id,sourceFile:d.sourceFile,rows:d.rows,inserted,repeated}],{session:s});dataset.lastImportedAt=new Date();dataset.version++;await dataset.save({session:s});return {_id:batch._id,inserted,repeated};
 });}
 private filter(a:AuthUser,id:string,q:D.BiQuery){const period=this.period(q);return {tenantId:this.store.id(a.tenantId!),datasetId:this.store.id(id),date:{$gte:period.from,$lte:period.to},...(q.category?{category:q.category}:{})};}
 async records(u:AuthUser,id:string,q:D.BiQuery,permission='bi.visualizar'){const a=await this.store.access.require(u,[permission]);await this.dataset(a,id);return this.store.page('BiRecord',this.filter(a,id,q),q,{date:1,_id:1},'-fingerprint');}
 async dashboard(u:AuthUser,id:string,q:D.BiQuery){const a=await this.store.access.require(u,['bi.visualizar']),dataset=await this.dataset(a,id),filter=this.filter(a,id,q),period=this.period(q);const [result]=await this.model('BiRecord').aggregate([{$match:filter},{$facet:{totals:[{$group:{_id:null,value:{$sum:'$value'},count:{$sum:1},firstDate:{$min:'$date'},lastDate:{$max:'$date'}}}],months:[{$group:{_id:{$substrBytes:['$date',0,7]},value:{$sum:'$value'},count:{$sum:1}}},{$sort:{_id:1}}],categories:[{$group:{_id:'$category',value:{$sum:'$value'},count:{$sum:1}}},{$sort:{value:-1,_id:1}},{$limit:50}]}}]).option({maxTimeMS:10000});
  const goals=await this.model('BiGoal').find({tenantId:a.tenantId,datasetId:id,month:{$gte:period.from.slice(0,7),$lte:period.to.slice(0,7)}}).select('-inputHash -requestId').lean();
  return {dataset:this.clean(dataset),period,totals:result.totals[0]??{value:null,count:0,firstDate:null,lastDate:null},months:result.months,categories:result.categories,goals:goals.map((g:any)=>{const monthEnd=new Date(g.month+'-01T12:00:00Z');monthEnd.setUTCMonth(monthEnd.getUTCMonth()+1);monthEnd.setUTCDate(0);const full=period.from<=g.month+'-01'&&period.to>=monthEnd.toISOString().slice(0,10),actual=result.months.find((m:any)=>m._id===g.month)?.value??null;return {...g,actual,assessment:q.category?'FILTERED_SCOPE':!full?'PARTIAL_PERIOD':actual===null?'NO_DATA':g.direction==='AT_LEAST'?(actual>=g.target?'MET':'BELOW_TARGET'):(actual<=g.target?'MET':'ABOVE_LIMIT')};}),formula:'Soma dos valores dos registros identificados. Uma fonte por painel; fontes externas e internas não são somadas automaticamente.',refreshedAt:new Date()};
 }
 async goal(u:AuthUser,id:string,d:D.BiGoalDto){this.date(d.month+'-01');return this.write(u,'bi.configurar','bi.goal.created',async(a,s)=>{await this.dataset(a,id,s);const payload={...d,datasetId:id},previous=await this.store.replay('BiGoal',a,payload,s);if(previous)return this.clean(previous);if(await this.model('BiGoal').exists({tenantId:a.tenantId,datasetId:id,month:d.month}).session(s))throw new ConflictException('Meta já definida para esta competência.');const [g]=await this.model('BiGoal').create([{...d,...this.store.fields(a,payload),datasetId:id}],{session:s});return this.clean(g);});}
 async export(u:AuthUser,id:string,q:D.BiQuery){const rows=await this.records(u,id,q,'bi.exportar');return '\uFEFF'+[['Chave','Data','Valor na unidade da fonte','Categoria'],...rows.items.map((r:any)=>[r.key,r.date,r.value,r.category])].map(row=>row.map(csvCell).join(';')).join('\r\n');}
 async operations(u:AuthUser,q:D.BiQuery){const a=await this.store.access.require(u,['bi.visualizar']),period=this.period(q),tenantId=this.store.id(a.tenantId!),cards=[];
  if(a.permissions?.includes('vendas.visualizar')){const dates={$dateToString:{format:'%Y-%m-%d',date:'$finalizedAt',timezone:'America/Sao_Paulo'}};const [r]=await this.model('Order').aggregate([{$match:{tenantId,status:'FINALIZED',...(OWNERS.includes(a.role!)?{}:{openedById:this.store.id(a.sub)}),$expr:{$and:[{$gte:[dates,period.from]},{$lte:[dates,period.to]}]}}},{$group:{_id:null,amountCents:{$sum:'$totalCents'},count:{$sum:1}}}]).option({maxTimeMS:10000});cards.push({code:'COMPLETED_SALES',name:'Vendas finalizadas',amountCents:r?.amountCents??null,count:r?.count??0,scope:OWNERS.includes(a.role!)?'COMPANY':'OWN',definition:'Soma dos totais das vendas atualmente finalizadas, pela data de finalização em America/Sao_Paulo. Exclui canceladas e estornadas; não representa notas fiscais emitidas.'});}
  if(a.permissions?.includes('tesouraria.visualizar')){const rows=await this.model('CashEntry').aggregate([{$match:{tenantId,status:'SETTLED',settledDate:{$gte:period.from,$lte:period.to}}},{$group:{_id:'$direction',amountCents:{$sum:'$amountCents'},count:{$sum:1}}}]);for(const direction of ['IN','OUT']){const r=rows.find(row=>row._id===direction);cards.push({code:'TREASURY_'+direction,name:direction==='IN'?'Entradas liquidadas':'Saídas liquidadas',amountCents:r?.amountCents??null,count:r?.count??0,scope:'COMPANY',definition:'Lançamentos liquidados da tesouraria pela data da liquidação. Inclui transferências internas; não equivale a receita ou despesa econômica.'});}}
  return {period,cards,refreshedAt:new Date(),note:'Fontes exibidas somente quando o módulo e a permissão operacional estão liberados. Importações externas permanecem em painéis separados.'};
 }
}
