import { Component,signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DatePipe } from '@angular/common';
import { CommerceApi } from './commerce-api.service';
@Component({selector:'app-leads',standalone:true,imports:[FormsModule,DatePipe],template:`<section class="commerce"><h2>Interessados e soluções sugeridas</h2><p>Contatos enviados pelo diagnóstico da página pública.</p>@if(message()){<p role="status" class="notice">{{message()}}</p>}@if(!emailConfigured()){<p class="notice">Envio de e-mail ainda não configurado neste ambiente. As solicitações ficam registradas aqui.</p>}<form (ngSubmit)="page=1;load()"><div class="fields"><label>Pesquisar nome, e-mail ou telefone<input name="search" [(ngModel)]="search" maxlength="120"></label><label>Situação<select name="status" [(ngModel)]="status"><option value="">Todas</option><option value="NEW">Novos</option><option value="CONTACTED">Contatados</option><option value="CLOSED">Concluídos</option></select></label></div><button [disabled]="busy()">Pesquisar</button></form>@for(lead of rows();track lead._id){<article class="panel"><header><h3>{{lead.name}}</h3><span>{{lead.createdAt|date:'dd/MM/yyyy HH:mm'}}</span></header><p>{{lead.email}} · {{lead.phone}}</p><p>Situação: {{labels[lead.status]}} · E-mail: {{labels[lead.emailStatus]}}</p><h4>Problema informado</h4><p style="white-space:pre-wrap">{{lead.problem}}</p><h4>Solução sugerida</h4><p>{{lead.recommendation.plan?.name||'Módulos personalizados / análise individual'}}</p>@for(m of lead.recommendation.modules;track m.code){<p><strong>{{m.name}}</strong> — {{m.reason}}</p>}<p>Observação: {{lead.note||'Nenhuma'}}</p><label>Registrar acompanhamento<textarea [(ngModel)]="notes[lead._id]" maxlength="500"></textarea></label><div class="actions"><button (click)="update(lead,'CONTACTED')" [disabled]="busy()||(notes[lead._id]||'').trim().length<5">Marcar como contatado</button><button (click)="update(lead,'CLOSED')" [disabled]="busy()||(notes[lead._id]||'').trim().length<5">Concluir atendimento</button></div></article>}@empty{<p>Nenhuma solicitação encontrada.</p>}<nav aria-label="Paginação de interessados"><button (click)="page=page-1;load()" [disabled]="busy()||page<=1">Anterior</button><span>Página {{page}} · {{total}} contatos</span><button (click)="page=page+1;load()" [disabled]="busy()||page*20>=total">Próxima</button></nav></section>`,styleUrl:'./commerce.scss'})
export class LeadsComponent {
 rows=signal<any[]>([]);busy=signal(false);message=signal('');emailConfigured=signal(false);page=1;total=0;search='';status='';notes:Record<string,string>={};
 labels:Record<string,string>={NEW:'Novo',CONTACTED:'Contatado',CLOSED:'Concluído',PENDING:'Na fila',PROCESSING:'Enviando',ACCEPTED:'Aceito pelo provedor',FAILED:'Revisão necessária'};
 constructor(private api:CommerceApi){this.load();}
 load(){if(this.busy())return;this.busy.set(true);this.api.get<any>(`platform/leads?page=${this.page}&limit=20${this.search?'&search='+encodeURIComponent(this.search):''}${this.status?'&status='+this.status:''}`).subscribe({next:p=>{this.rows.set(p.items);this.total=p.total;this.emailConfigured.set(p.emailConfigured);this.busy.set(false);},error:e=>this.fail(e)});}
 update(lead:any,status:string){if(this.busy())return;this.busy.set(true);this.api.post(`platform/leads/${lead._id}/status`,{status,version:lead.version,reason:this.notes[lead._id]}).subscribe({next:()=>{this.busy.set(false);this.message.set('Acompanhamento atualizado.');this.load();},error:e=>this.fail(e)});}
 fail(e:any){this.busy.set(false);const m=e.error?.message;this.message.set(Array.isArray(m)?m.join(' '):m??'Não foi possível carregar as solicitações.');}
}
