export enum FinancialType { DESPESA_OPERACIONAL = 'DESPESA_OPERACIONAL', CUSTO_PRODUCAO = 'CUSTO_PRODUCAO', DESPESA_PESSOAL = 'DESPESA_PESSOAL' }
export enum FinancialNature { FIXA = 'FIXA', VARIAVEL = 'VARIAVEL' }
export enum FinancialStatus { PENDENTE = 'PENDENTE', PAGO = 'PAGO', VENCIDO = 'VENCIDO', CANCELADO = 'CANCELADO' }
export enum FinancialFrequency { SEMANAL = 'SEMANAL', MENSAL = 'MENSAL', ANUAL = 'ANUAL' }
export enum FinancialOrigin { PF = 'PF', PJ = 'PJ' }
export enum FinancialPaymentMethod { DINHEIRO = 'DINHEIRO', PIX = 'PIX', DEBITO = 'DEBITO', CREDITO = 'CREDITO', BOLETO = 'BOLETO', TRANSFERENCIA = 'TRANSFERENCIA', OUTRO = 'OUTRO' }
export enum FinancialUnit { KG = 'KG', G = 'G', L = 'L', ML = 'ML', UNIDADE = 'UNIDADE', CAIXA = 'CAIXA', PACOTE = 'PACOTE' }
export enum FinancialAction { CRIACAO = 'CRIACAO', EDICAO = 'EDICAO', PAGAMENTO = 'PAGAMENTO', CORRECAO_PAGAMENTO = 'CORRECAO_PAGAMENTO', CANCELAMENTO = 'CANCELAMENTO' }

export enum EntryKind { OPERATING_EXPENSE='OPERATING_EXPENSE', PRODUCTION_COST='PRODUCTION_COST', INPUT_PURCHASE='INPUT_PURCHASE', RECURRING='RECURRING', PERSONAL_EXPENSE='PERSONAL_EXPENSE' }
