import { Routes } from '@angular/router';
import { authGuard, roleGuard, waitingGuard, sessionGuard, permissionGuard } from './core/auth.guard';

export const routes: Routes = [
  { path:'empresa/:slug', loadComponent:()=>import('./features/catalog/public-catalog.component').then(m=>m.PublicCatalogComponent) },
  { path:'vitrine/preview',canActivate:[permissionGuard('landing_page.visualizar')],data:{preview:true},loadComponent:()=>import('./features/catalog/public-catalog.component').then(m=>m.PublicCatalogComponent) },
  { path:'', pathMatch:'full', loadComponent:()=>import('./features/landing/landing.component').then(m=>m.LandingComponent) },
  { path:'meu-perfil', canActivate:[sessionGuard], loadComponent:()=>import('./layout/shell.component').then(m=>m.ShellComponent), children:[
    {path:'',loadComponent:()=>import('./features/profile/profile.component').then(m=>m.ProfileComponent)},
  ] },
  { path: 'cadastrar-empresa', loadComponent: () => import('./features/tenancy/registration.component').then(m => m.RegistrationComponent) },
  { path: 'solicitar-acesso', loadComponent: () => import('./features/tenancy/registration.component').then(m => m.RegistrationComponent) },
  { path: 'aguardando-aprovacao', canActivate: [waitingGuard], loadComponent: () => import('./features/tenancy/waiting.component').then(m => m.WaitingComponent) },
  { path: 'plataforma/login', loadComponent: () => import('./features/login/login.component').then(m => m.LoginComponent) },
  { path: 'plataforma/empresas', canActivate: [roleGuard('PLATFORM_ADMIN')], loadComponent: () => import('./features/tenancy/platform.component').then(m => m.PlatformComponent) },
  { path: 'plataforma/comercial', canActivate: [roleGuard('PLATFORM_ADMIN')], loadComponent: () => import('./features/tenancy/platform.component').then(m => m.PlatformComponent) },
  { path: 'login', loadComponent: () => import('./features/login/login.component').then(m => m.LoginComponent) },
  {
    path: '',
    canActivate: [authGuard],
    canActivateChild: [authGuard],
    loadComponent: () => import('./layout/shell.component').then(m => m.ShellComponent),
    children: [
      {path:'crm',canActivate:[permissionGuard('crm.visualizar')],loadComponent:()=>import('./features/crm/crm.component').then(m=>m.CrmComponent)},
      {path:'servicos',canActivate:[permissionGuard('servicos.visualizar')],loadComponent:()=>import('./features/service-orders/service-orders.component').then(m=>m.ServiceOrdersComponent)},
      {path:'contratos',canActivate:[permissionGuard('contratos.visualizar')],loadComponent:()=>import('./features/contracts/contracts.component').then(m=>m.ContractsComponent)},
      {path:'fidelidade',canActivate:[permissionGuard('fidelidade.visualizar')],loadComponent:()=>import('./features/loyalty/loyalty.component').then(m=>m.LoyaltyComponent)},
      {path:'projetos',canActivate:[permissionGuard('projetos.visualizar')],loadComponent:()=>import('./features/projects/projects.component').then(m=>m.ProjectsComponent)},
      {path:'compras',canActivate:[permissionGuard('compras.visualizar')],loadComponent:()=>import('./features/purchases/purchases.component').then(m=>m.PurchasesComponent)},
      {path:'logistica',canActivate:[permissionGuard('logistica.visualizar')],loadComponent:()=>import('./features/logistics/logistics.component').then(m=>m.LogisticsComponent)},
      {path:'bi',canActivate:[permissionGuard('bi.visualizar')],loadComponent:()=>import('./features/bi/bi.component').then(m=>m.BiComponent)},
      {path:'documentos',canActivate:[permissionGuard('documentos.visualizar')],loadComponent:()=>import('./features/documents/documents.component').then(m=>m.DocumentsComponent)},
      {path:'filiais',canActivate:[permissionGuard('filiais.visualizar')],loadComponent:()=>import('./features/branches/branches.component').then(m=>m.BranchesComponent)},
      {path:'estoque',canActivate:[permissionGuard('estoque.visualizar')],loadComponent:()=>import('./features/inventory/stock.component').then(m=>m.StockComponent)},
      {path:'auditoria',canActivate:[permissionGuard('auditoria.visualizar')],loadComponent:()=>import('./features/audit/audit.component').then(m=>m.AuditComponent)},
      {path:'qualidade',canActivate:[permissionGuard('qualidade.visualizar')],loadComponent:()=>import('./features/inventory/quality.component').then(m=>m.QualityComponent)},
      {path:'assinatura',canActivate:[roleGuard('OWNER','ADMIN')],loadComponent:()=>import('./features/commerce/subscription.component').then(m=>m.SubscriptionComponent)},
      {path:'categorias',canActivate:[permissionGuard('categorias.visualizar')],loadComponent:()=>import('./features/catalog/categories.component').then(m=>m.CategoriesComponent)},
      {path:'vitrine',canActivate:[permissionGuard('landing_page.visualizar')],loadComponent:()=>import('./features/catalog/landing-config.component').then(m=>m.LandingConfigComponent)},
      {path:'cargos',canActivate:[permissionGuard('cargos.visualizar')],loadComponent:()=>import('./features/catalog/roles.component').then(m=>m.RolesComponent)},
      { path: 'insumos', canActivate: [permissionGuard('estoque.visualizar','producao.visualizar')], loadComponent: () => import('./features/inventory/inventory.component').then(m => m.InventoryComponent) },
      { path: 'despesas', canActivate: [permissionGuard('financeiro.visualizar')], loadComponent: () => import('./features/finance/finance.component').then(m => m.FinanceComponent) },
      {path:'financeiro',canActivate:[permissionGuard('tesouraria.visualizar')],data:{mode:'treasury'},loadComponent:()=>import('./features/business/business.component').then(m=>m.BusinessComponent)},
      {path:'contabil',canActivate:[permissionGuard('contabil.visualizar')],data:{mode:'accounting'},loadComponent:()=>import('./features/business/business.component').then(m=>m.BusinessComponent)},
      {path:'cadastros',canActivate:[permissionGuard('cadastros.visualizar')],data:{mode:'parties'},loadComponent:()=>import('./features/business/business.component').then(m=>m.BusinessComponent)},
      { path: 'inicio', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
      { path: 'vendas', canActivate: [permissionGuard('vendas.visualizar')], loadComponent: () => import('./features/pos/pos.component').then(m => m.PosComponent) },
      { path: 'cozinha', canActivate: [permissionGuard('producao.visualizar')], loadComponent: () => import('./features/kitchen/kitchen.component').then(m => m.KitchenComponent) },
      { path: 'dashboard', canActivate: [permissionGuard('relatorios.visualizar','financeiro.visualizar')], loadComponent: () => import('./features/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'produtos', canActivate: [permissionGuard('produtos.visualizar','categorias.visualizar')], loadComponent: () => import('./features/products/products.component').then(m => m.ProductsComponent) },
      { path: 'usuarios', canActivate: [permissionGuard('usuarios.visualizar')], loadComponent: () => import('./features/users/users.component').then(m => m.UsersComponent) },
    ],
  },
  { path: '**', redirectTo: '' },
];
