export enum UserRole {
  MEMBER = 'MEMBER',
  ADMIN = 'ADMIN',
  OWNER = 'OWNER',
  ACCOUNTANT = 'ACCOUNTANT',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  KITCHEN = 'KITCHEN',
  CASHIER = 'CASHIER',
}

export enum OrderType {
  DINE_IN = 'DINE_IN',
  TAKEAWAY = 'TAKEAWAY',
}

export enum OrderStatus {
  OPEN = 'OPEN',
  FINALIZED = 'FINALIZED',
  CANCELED = 'CANCELED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  PIX = 'PIX',
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum StockMovementType {
  SERVICE_CONSUMPTION = 'SERVICE_CONSUMPTION',
  SALE = 'SALE',
  PURCHASE = 'PURCHASE',
  PRODUCTION = 'PRODUCTION',
  ORDER_RESERVATION = 'ORDER_RESERVATION',
  ORDER_RELEASE = 'ORDER_RELEASE',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}

export enum AvailabilityMode {
  PRODUCTION_CONTROLLED = 'PRODUCTION_CONTROLLED',
  MADE_TO_ORDER = 'MADE_TO_ORDER',
}

export enum SupplyMode {
  CONTROLADO_POR_ESTOQUE = 'CONTROLADO_POR_ESTOQUE',
  PRODUZIDO_SOB_DEMANDA = 'PRODUZIDO_SOB_DEMANDA',
  COMPRADO_SOB_DEMANDA = 'COMPRADO_SOB_DEMANDA',
}

export enum UserStatus { PENDING = 'PENDING', ACTIVE = 'ACTIVE', REJECTED = 'REJECTED', INACTIVE = 'INACTIVE' }
export enum TenantStatus { PENDING = 'PENDING', ACTIVE = 'ACTIVE', REJECTED = 'REJECTED', SUSPENDED = 'SUSPENDED', INACTIVE = 'INACTIVE' }

export enum ProductOrigin { PRODUCED='PRODUCED', PURCHASED_FOR_RESALE='PURCHASED_FOR_RESALE' }
export enum SalesGroup { SNACKS='SNACKS', BEVERAGES='BEVERAGES', OTHER='OTHER' }
