import { describe, expect, it } from 'vitest';
import { buildOverview } from './overview.service.js';
const product={_id:'p',name:'Produto',active:true,availableStock:2,minimumStock:3,availabilityMode:'PRODUCTION_CONTROLLED',origin:'PRODUCED'};
const order={totalCents:1000,finalizedAt:new Date('2026-09-02T02:30:00Z'),items:[{productId:'p',name:'Nome histórico',quantity:2,unitPriceCents:500,origin:'PRODUCED'}]};
const entry=(type:string,expectedAmountCents:number,status='PENDENTE')=>({type,expectedAmountCents,status});
describe('overview monthly business indicators',()=>{
 it('separates estimated financial result and ingredient ledger cost',()=>{const r=buildOverview('2026-09',[order],[{productId:'p',productName:'Produto',quantity:4,createdAt:new Date('2026-09-01T13:00:00Z'),ingredientCostCents:80}],[entry('CUSTO_PRODUCAO',200),entry('DESPESA_OPERACIONAL',300),entry('DESPESA_PESSOAL',999),entry('CUSTO_PRODUCAO',999,'CANCELADO')],[product]);expect(r.financial).toMatchObject({revenueCents:1000,grossProfitCents:800,operatingResultCents:500,operatingMarginPercent:50,operationalCoverageGapCents:0});expect(r.productionCost).toEqual({recordedCents:80,coveredQuantity:4,uncoveredQuantity:0});expect(r.surplus[0]).toMatchObject({difference:2,availableStock:2});});
 it('returns null margin without revenue and full expense coverage gap',()=>{const r=buildOverview('2026-09',[],[],[entry('DESPESA_OPERACIONAL',500)],[]);expect(r.financial.operatingMarginPercent).toBeNull();expect(r.financial.operationalCoverageGapCents).toBe(500);expect(r.financial.operatingResultCents).toBe(-500);expect(r.trend).toHaveLength(30);expect(r.heatmap).toHaveLength(168);});
 it('groups by local finalized hour/day across UTC day boundary',()=>{const r=buildOverview('2026-09',[order],[],[],[product]);expect(r.trend[0].soldQuantity).toBe(2);expect(r.trend[1].soldQuantity).toBe(0);expect(r.heatmap.find(x=>x.weekday===2&&x.hour===23)?.orderCount).toBe(1);});
 it('excludes resale from manufacturing curve but includes it in revenue ranking',()=>{const r=buildOverview('2026-09',[{...order,totalCents:1300,items:[...order.items,{productId:'b',name:'Bebida',quantity:3,unitPriceCents:100,origin:'PURCHASED_FOR_RESALE'}]}],[],[],[product]);expect(r.trend[0].soldQuantity).toBe(2);expect(r.topQuantity[0].name).toBe('Bebida');expect(r.topRevenue[0].name).toBe('Nome histórico');});
 it('uses current product origin only for old snapshots without origin',()=>{const r=buildOverview('2026-09',[{...order,items:[{...order.items[0],origin:undefined}]}],[],[],[product]);expect(r.trend[0].soldQuantity).toBe(2);});
 it('does not flag made-to-order or inactive products as low physical stock',()=>{const r=buildOverview('2026-09',[],[],[],[product,{...product,_id:'b',availabilityMode:'MADE_TO_ORDER',availableStock:-5},{...product,_id:'c',active:false}]);expect(r.lowStock.map(x=>x.productId)).toEqual(['p']);});
 it('shows negative margin and nonzero gap when expenses exceed revenue',()=>{const r=buildOverview('2026-09',[order],[],[entry('CUSTO_PRODUCAO',400),entry('DESPESA_OPERACIONAL',1500)],[]);expect(r.financial.operatingMarginPercent).toBe(-90);expect(r.financial.operationalCoverageGapCents).toBe(500);});
 it('limits ranking to five after summing, with historical prices',()=>{const items=Array.from({length:7},(_,i)=>({productId:String(i),name:`Item${i}`,quantity:i+1,unitPriceCents:100,origin:'PRODUCED'}));const r=buildOverview('2026-09',[{...order,items,totalCents:2800}],[],[],[]);expect(r.topQuantity).toHaveLength(5);expect(r.topQuantity[0]).toMatchObject({quantity:7,revenueCents:700,revenueSharePercent:25});});
 it('distinguishes productions without technical costing',()=>{const r=buildOverview('2026-09',[],[{productId:'p',productName:'Produto',quantity:10,createdAt:new Date('2026-09-10T10:00:00Z')}],[],[]);expect(r.productionCost.uncoveredQuantity).toBe(10);expect(r.productionCost.coveredQuantity).toBe(0);});
 it('rejects unsafe aggregate money and invalid month',()=>{expect(()=>buildOverview('2026-09',[{...order,totalCents:Number.MAX_SAFE_INTEGER},order],[],[],[])).toThrow();expect(()=>buildOverview('2026-13',[],[],[],[])).toThrow();});
});
