import { Component, signal } from '@angular/core';
import { CurrencyPipe, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { CommerceApi, parsePrice } from '../commerce/commerce-api.service';
import { AuthService } from '../../core/auth.service';
@Component({selector:'app-service-orders',standalone:true,imports:[FormsModule,CurrencyPipe,DatePipe],templateUrl:'./service-orders.component.html',styleUrls:['../business/business.component.scss','../crm/crm.component.scss']})
export class ServiceOrdersComponent {
  tab='appointments';page=1;total=0;search='';status='';from='';to='';reason='';rescheduleAt='';
  busy=signal(false);message=signal('');rows=signal<any[]>([]);selected=signal<any>(null);services=signal<any[]>([]);resources=signal<any[]>([]);people=signal<any[]>([]);parties=signal<any[]>([]);products=signal<any[]>([]);
  service={name:'',description:'',durationMinutes:60,preparationMinutes:10,price:'0'};resource={name:'',location:''};contactName='';
  booking={partyId:'',serviceId:'',assignedId:'',resourceId:'',startsAt:'',notes:''};
  order={partyId:'',serviceId:'',assignedId:'',appointmentId:'',title:'',equipment:'',location:'',request:'',priority:'NORMAL',dueAt:'',materials:[] as {productId:string;description:string;quantity:number;price:string}[]};
  completion={report:'',checks:[{name:'Serviço executado',passed:false,evidence:''},{name:'Conferência final',passed:false,evidence:''}],materials:[] as {productId?:string;description:string;quantity:number}[]};
  labels:Record<string,string>={BOOKED:'Agendado',CONFIRMED:'Confirmado',ARRIVED:'Cliente presente',IN_PROGRESS:'Em execução',DONE:'Atendimento concluído',NO_SHOW:'Não compareceu',CANCELED:'Cancelado',OPEN:'Aberta',ANALYSIS:'Em análise',WAITING_APPROVAL:'Aguardando aprovação',APPROVED:'Aprovada',COMPLETED:'Concluída',DELIVERED:'Entregue',LOW:'Baixa',NORMAL:'Normal',HIGH:'Alta',URGENT:'Urgente'};
  private keys=new Map<string,string>();
  constructor(private api:CommerceApi,public auth:AuthService){this.booking.assignedId=auth.user()!.sub;this.order.assignedId=auth.user()!.sub;void this.load();}
  private async get(path:string){return firstValueFrom(this.api.get<any>('service-orders/'+path));}
  private fail(e:any){const m=e.error?.message??e.message;this.message.set(Array.isArray(m)?m.join(' '):m??'Não foi possível concluir.');}
  private async catalog(path:string){let page=1,items:any[]=[];while(true){const r=await this.get(`${path}?page=${page}&limit=100`);items.push(...r.items);if(items.length>=r.total||!r.items.length)return items;page++;}}
  async load(){if(this.busy())return;this.busy.set(true);try{if(!!this.from!==!!this.to)throw new Error('Informe início e fim do período.');const q=new URLSearchParams({page:String(this.page),limit:'20',search:this.search});if(this.status)q.set('status',this.status);if(this.from&&this.to){q.set('from',new Date(this.from).toISOString());q.set('to',new Date(this.to).toISOString());}const [r,services,resources,people,parties,products]=await Promise.all([this.get(`${this.tab}?${q}`),this.catalog('services'),this.catalog('resources'),this.catalog('people'),this.catalog('parties'),this.catalog('products')]);this.rows.set(r.items);this.total=r.total;this.services.set(services);this.resources.set(resources);this.people.set(people);this.parties.set(parties);this.products.set(products);}catch(e){this.fail(e);}finally{this.busy.set(false);}}
  choose(tab:string){this.tab=tab;this.page=1;this.status='';this.rows.set([]);this.selected.set(null);void this.load();}
  private money(text:string){const n=parsePrice(text);if(n===null)throw new Error('Informe reais com até duas casas decimais.');return n;}
  async save(path:string,body:any,create=false,central=false){if(this.busy())return;this.busy.set(true);try{let requestId=this.keys.get(path);if(create&&!requestId){requestId=crypto.randomUUID();this.keys.set(path,requestId);}const result=await firstValueFrom(this.api.post<any>((central?'':'service-orders/')+path,{...body,...(create?{requestId}:{})}));this.keys.delete(path);this.message.set('Operação salva.');return result;}catch(e){this.fail(e);return null;}finally{this.busy.set(false);}}
  async createService(){try{const {price,...data}=this.service;if(await this.save('services',{...data,priceCents:this.money(price)},true)){this.service.name='';await this.load();}}catch(e){this.fail(e);}}
  async createResource(){if(await this.save('resources',this.resource,true)){this.resource.name='';await this.load();}}
  async createContact(){if(await this.save('parties',{name:this.contactName,roles:['CUSTOMER'],notes:''},false,true)){this.contactName='';await this.load();}}
  async book(){try{const data={...this.booking,resourceId:this.booking.resourceId||undefined,startsAt:new Date(this.booking.startsAt).toISOString()};if(await this.save('appointments',data,true))await this.load();}catch(e){this.fail(e);}}
  async state(row:any,status:string){if(this.reason.trim().length<5)return;if(status==='CANCELED'&&!window.confirm('Cancelar este registro?'))return;const result=await this.save(`${this.tab}/${row._id}/status`,{version:row.version,status,reason:this.reason});if(result){if(this.tab==='orders')this.selected.set(result);await this.load();}}
  async reschedule(row:any){try{if(await this.save(`appointments/${row._id}/reschedule`,{version:row.version,reason:this.reason,startsAt:new Date(this.rescheduleAt).toISOString()}))await this.load();}catch(e){this.fail(e);}}
  fromBooking(row:any){this.order={...this.order,partyId:row.partyId,serviceId:row.serviceId,assignedId:row.assignedId,appointmentId:row._id,title:row.serviceName,request:row.notes||'',dueAt:new Date(new Date(row.endsAt).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)};this.choose('orders');}
  addMaterial(){if(this.order.materials.length<100)this.order.materials.push({productId:'',description:'',quantity:1,price:'0'});}
  product(line:any){if(line.productId)line.description=this.products().find(p=>p._id===line.productId)?.name??line.description;}
  async createOrder(){try{const data={...this.order,appointmentId:this.order.appointmentId||undefined,dueAt:new Date(this.order.dueAt).toISOString(),materials:this.order.materials.map(({price,productId,...m})=>({...m,productId:productId||undefined,unitCents:this.money(price)}))};if(await this.save('orders',data,true)){this.order.title='';this.order.appointmentId='';await this.load();}}catch(e){this.fail(e);}}
  async open(row:any){if(this.busy())return;this.busy.set(true);try{const r=await this.get(`orders/${row._id}`);this.selected.set(r);this.completion.materials=r.materials.map((m:any)=>({productId:m.productId,description:m.description,quantity:m.quantity}));this.completion.report='';this.completion.checks.forEach(c=>{c.passed=false;c.evidence='';});}catch(e){this.fail(e);}finally{this.busy.set(false);}}
  async complete(){const row=this.selected();if(!window.confirm('Concluir a ordem e registrar o consumo informado?'))return;const result=await this.save(`orders/${row._id}/complete`,{...this.completion,version:row.version,reason:this.reason});if(result){this.selected.set(result);await this.load();}}
  actions(row:any){const map:Record<string,string[]> = this.tab==='appointments'?{BOOKED:['CONFIRMED','ARRIVED','NO_SHOW','CANCELED'],CONFIRMED:['ARRIVED','NO_SHOW','CANCELED'],ARRIVED:['IN_PROGRESS','CANCELED'],IN_PROGRESS:['DONE']}:{OPEN:['ANALYSIS','CANCELED'],ANALYSIS:['WAITING_APPROVAL','CANCELED'],WAITING_APPROVAL:['APPROVED','CANCELED'],APPROVED:['IN_PROGRESS','CANCELED'],IN_PROGRESS:['CANCELED'],COMPLETED:['DELIVERED']};return (map[row.status]??[]).filter(status=>status==='CANCELED'?this.auth.can('servicos.cancelar'):this.tab==='appointments'?this.auth.can('servicos.agendar'):status==='APPROVED'?this.auth.can('servicos.aprovar','servicos.valores'):this.auth.can('servicos.executar'));}
}
