import { Schema, Types } from 'mongoose';
const options={timestamps:true,autoCreate:false,autoIndex:false,strict:'throw' as const};
const oid={type:Schema.Types.ObjectId,required:true};
const money={type:Number,required:true,min:0,max:1_000_000_000_000,validate:Number.isSafeInteger};
const base={tenantId:{...oid,immutable:true},actorId:oid,version:{type:Number,default:0,min:0,validate:Number.isSafeInteger}};
const text=(max:number)=>({type:String,trim:true,maxlength:max});
export interface Party {tenantId:Types.ObjectId;name:string;roles:string[];email?:string;phone?:string;notes?:string;active:boolean;version:number;actorId:Types.ObjectId}
const party=new Schema<Party>({...base,name:{...text(160),required:true},roles:[{type:String,enum:['CUSTOMER','SUPPLIER']}],email:text(254),phone:text(15),notes:text(2000),active:{type:Boolean,default:true}},{...options,collection:'business_parties_v2'});
party.index({tenantId:1,name:1,_id:1});
export interface CashAccount {tenantId:Types.ObjectId;actorId:Types.ObjectId;name:string;kind:string;openingCents:number;active:boolean;version:number}
const cashAccount=new Schema<CashAccount>({...base,name:{...text(100),required:true},kind:{type:String,enum:['BANK','CASH','WALLET'],required:true},openingCents:{...money,min:-1_000_000_000_000},active:{type:Boolean,default:true}},{...options,collection:'treasury_accounts_v2'});cashAccount.index({tenantId:1,name:1});
export interface CashEntry {tenantId:Types.ObjectId;actorId:Types.ObjectId;accountId:Types.ObjectId;partyId?:Types.ObjectId;description:string;direction:'IN'|'OUT';amountCents:number;dueDate:string;settledDate?:string;status:string;reference:string;version:number;reason?:string}
const cashEntry=new Schema<CashEntry>({...base,accountId:oid,partyId:Schema.Types.ObjectId,description:{...text(200),required:true},direction:{type:String,enum:['IN','OUT'],required:true},amountCents:{...money,min:1},dueDate:{type:String,required:true},settledDate:String,status:{type:String,enum:['PENDING','SETTLED','CANCELED'],default:'PENDING'},reference:{...text(100),required:true},reason:text(500)},{...options,collection:'treasury_entries_v2'});cashEntry.index({tenantId:1,reference:1},{unique:true});cashEntry.index({tenantId:1,status:1,dueDate:1});
export interface LedgerAccount {tenantId:Types.ObjectId;actorId:Types.ObjectId;code:string;name:string;kind:'ASSET'|'LIABILITY'|'EQUITY'|'REVENUE'|'EXPENSE';active:boolean;version:number}
const ledgerAccount=new Schema<LedgerAccount>({...base,code:{...text(30),required:true},name:{...text(160),required:true},kind:{type:String,enum:['ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE'],required:true},active:{type:Boolean,default:true}},{...options,collection:'accounting_accounts_v2'});ledgerAccount.index({tenantId:1,code:1},{unique:true});
export interface JournalLine {accountId:Types.ObjectId;code:string;name:string;kind:string;debitCents:number;creditCents:number}
export interface Journal {tenantId:Types.ObjectId;actorId:Types.ObjectId;date:string;description:string;reference:string;source:string;sourceId?:Types.ObjectId;reversalOf?:Types.ObjectId;lines:JournalLine[];totalCents:number;version:number}
const journal=new Schema<Journal>({...base,date:{type:String,required:true},description:{...text(500),required:true},reference:{...text(100),required:true},source:{type:String,enum:['MANUAL','SALE','EXPENSE','TREASURY','REVERSAL'],required:true},sourceId:Schema.Types.ObjectId,reversalOf:Schema.Types.ObjectId,totalCents:money,lines:[new Schema({accountId:oid,code:text(30),name:text(160),kind:text(20),debitCents:money,creditCents:money},{_id:false,strict:'throw'})]},{...options,collection:'accounting_journals_v2'});journal.index({tenantId:1,reference:1},{unique:true});journal.index({tenantId:1,date:1,_id:1});journal.index({tenantId:1,reversalOf:1},{unique:true,partialFilterExpression:{reversalOf:{$type:'objectId'}}});journal.index({tenantId:1,source:1,sourceId:1},{unique:true,partialFilterExpression:{sourceId:{$type:'objectId'}}});
export interface Closing {tenantId:Types.ObjectId;actorId:Types.ObjectId;month:string;closed:boolean;reason:string;version:number}
const closing=new Schema<Closing>({...base,month:{type:String,required:true},closed:{type:Boolean,required:true},reason:{...text(500),required:true}},{...options,collection:'accounting_closings_v2'});closing.index({tenantId:1,month:1},{unique:true});
export interface Obligation {tenantId:Types.ObjectId;actorId:Types.ObjectId;name:string;dueDate:string;status:string;notes:string;version:number}
const obligation=new Schema<Obligation>({...base,name:{...text(160),required:true},dueDate:{type:String,required:true},status:{type:String,enum:['PENDING','DONE','NOT_APPLICABLE'],default:'PENDING'},notes:text(2000)},{...options,collection:'accounting_obligations_v2'});obligation.index({tenantId:1,dueDate:1});
export const BUSINESS_MODELS=[{name:'BusinessParty',schema:party},{name:'CashAccount',schema:cashAccount},{name:'CashEntry',schema:cashEntry},{name:'LedgerAccount',schema:ledgerAccount},{name:'Journal',schema:journal},{name:'AccountingClosing',schema:closing},{name:'AccountingObligation',schema:obligation}];
