import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
export async function usabilityBrowser(qa,state,check){
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{channel:'chrome'})});
 try{
 const context=await browser.newContext({baseURL:qa.baseURL,viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function login(role){const u=state.actors[role];await page.goto(role==='PLATFORM_ADMIN'?'/plataforma/login':'/login');if(role!=='PLATFORM_ADMIN')await page.locator('[name=cnpj]').fill(u.cnpj);await page.locator('[name=email]').fill(u.email);await page.locator('[name=password]').fill(u.password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.waitForURL(role==='ACCOUNTANT'?'**/financeiro':role==='PLATFORM_ADMIN'?'**/plataforma/empresas':'**/dashboard');}
 await login('OWNER');
 await check('browser profile read-only and masked company',async()=>{await page.goto('/meu-perfil');await page.getByRole('heading',{name:'Meu perfil'}).waitFor();await page.getByText(state.actors.OWNER.email,{exact:true}).waitFor();assert.equal(await page.locator('input').count(),0);assert.equal(await page.locator('main').innerText().then(t=>t.includes('somente leitura')),true);});
 await check('browser product visible button, Enter does not submit and click saves once',async()=>{await page.goto('/produtos');await page.locator('[name=name]').fill(`Browser product ${qa.run}`);await page.locator('[name=category]').fill('Bebidas');await page.locator('[name=price]').fill('6.50');await page.locator('[name=origin]').selectOption('PURCHASED_FOR_RESALE');await page.locator('[name=salesGroup]').selectOption('BEVERAGES');let calls=0;const listener=r=>{if(r.method()==='POST'&&r.url().endsWith('/api/products'))calls++;};page.on('request',listener);await page.locator('[name=name]').press('Enter');assert.equal(calls,0);const response=page.waitForResponse(r=>r.url().endsWith('/api/products')&&r.request().method()==='POST');await page.getByRole('button',{name:'Cadastrar produto',exact:true}).click();assert.equal((await response).status(),201);await page.getByText('Produto salvo.',{exact:true}).waitFor();assert.equal(calls,1);page.off('request',listener);});
 for(const width of [320,768,1440]){
  await page.setViewportSize({width,height:900});
  for(const [path,heading]of [['/produtos','Produtos'],['/vendas','Nova venda'],['/cozinha',null],['/financeiro',null],['/usuarios',null],['/dashboard',null],['/meu-perfil','Meu perfil']])await check(`browser responsive ${width}px ${path}`,async()=>{await page.goto(path);if(heading)await page.getByRole('heading',{name:heading,exact:true}).waitFor();else await page.locator('h1').first().waitFor();await page.evaluate(()=>document.fonts.ready);if(width===320)await page.screenshot({path:`${qa.out}/usability-${path.slice(1)}-320.png`,fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,'horizontal overflow: '+JSON.stringify(await page.locator('body *').evaluateAll(xs=>xs.filter(e=>e.getBoundingClientRect().right>innerWidth+1 && getComputedStyle(e).position!=='fixed').slice(0,15).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})))));assert.deepEqual(errors,[]);if(width===320)await page.screenshot({path:`${qa.out}/usability-${path.slice(1)}-320.png`,fullPage:true});});
 }
 for(const width of [320,768])await check(`browser product table keyboard scroll and actions ${width}px`,async()=>{
  await page.setViewportSize({width,height:900});await page.goto('/produtos');
  const region=page.getByRole('region',{name:'Lista de produtos'});await region.waitFor();
  assert.equal(await region.getAttribute('tabindex'),'0');await region.focus();
  assert.equal(await region.evaluate(e=>document.activeElement===e),true);
  assert.equal(await region.evaluate(e=>e.scrollWidth>e.clientWidth),true);
  await region.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.products-table-scroll')?.scrollLeft>0);
  const action=region.getByRole('button',{name:'Editar',exact:true}).first();await action.focus();
  assert.equal(await action.evaluate(e=>document.activeElement===e),true);
  assert.equal(await action.evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}),true);
  await action.press('Enter');await page.getByRole('button',{name:'Salvar produto',exact:true}).waitFor();
 });
 await check('browser sale groups/search exclude beverages from snacks',async()=>{await page.goto('/vendas');for(const name of ['Salgados','Bebidas','Outros'])await page.getByRole('heading',{name,exact:true}).waitFor();await page.getByRole('searchbox').fill('Refrigerante usability');await page.getByRole('button',{name:/Refrigerante usability/}).waitFor();assert.equal(await page.getByRole('button',{name:/Coxinha usability/}).count(),0);});
 await check('browser purchase paid today, detail and attachment upload',async()=>{await page.goto('/financeiro');await page.getByRole('button',{name:'Nova conta',exact:true}).click();await page.locator('[name=description]').fill('Frango browser');await page.locator('[name=type]').selectOption('CUSTO_PRODUCAO');await page.locator('[name=categoryId]').selectOption({label:'Insumos'});await page.locator('[name=amount]').fill('25,00');await page.locator('[name=entryKind]').selectOption('INPUT_PURCHASE');await page.locator('[name=paid]').check();const response=page.waitForResponse(r=>r.url().endsWith('/api/finance/entries')&&r.request().method()==='POST');await page.locator('form').getByRole('button',{name:'Salvar',exact:true}).click();const res=await response;assert.equal(res.status(),201);const body=await res.json();assert.equal(body.status,'PAGO');const row=page.locator('tr').filter({hasText:'Frango browser'});await row.getByRole('button',{name:/Detalhes|Ver/}).click();await page.locator('input[type=file]').setInputFiles({name:'nota.xml',mimeType:'application/xml',buffer:Buffer.from('<nota><item>Frango</item></nota>')});await page.getByText('Anexo enviado.',{exact:true}).waitFor();});
 await page.setViewportSize({width:320,height:900});
 await check('browser accountant fiscal area is read-only and printable/exportable',async()=>{await page.goto('/financeiro');await page.getByRole('button',{name:'Sair',exact:true}).click();await page.waitForURL('**/login');await login('ACCOUNTANT');await page.getByRole('button',{name:'Vendas para emissão fiscal',exact:true}).click();await page.locator('app-fiscal-sales').getByRole('button',{name:'Ver venda'}).first().waitFor();assert.equal(await page.locator('app-fiscal-sales').getByRole('button',{name:/Cancelar venda|Finalizar venda|Excluir venda/}).count(),0);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar CSV',exact:true}).click();assert.ok((await download).suggestedFilename().endsWith('.csv'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:`${qa.out}/usability-fiscal-320.png`,fullPage:true});});
 await check('browser phone paste/mask and confirmation feedback',async()=>{await page.goto('/cadastrar-empresa');await page.locator('[name=companyPhone]').fill('1133334444');assert.equal(await page.locator('[name=companyPhone]').inputValue(),'(11) 3333-4444');await page.locator('[name=companyPhone]').fill('11999999999');assert.equal(await page.locator('[name=companyPhone]').inputValue(),'(11) 99999-9999');await page.locator('[name=companyPhone]').press('a');assert.ok(!/[a-z]/i.test(await page.locator('[name=companyPhone]').inputValue()));await page.locator('[name=password]').fill('StrongUnique123!');await page.locator('[name=passwordConfirmation]').fill('DifferentUnique123!');await page.getByText('As senhas informadas não são iguais.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Cadastrar empresa',exact:true}).isDisabled(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);});
 await context.close();
 }finally{await browser.close();}
}
