import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { guard } from './tenancy-qa-harness.mjs';
export async function usabilityChecks(qa,check,browserEnabled=false){
 guard();const a=await qa.company(),b=await qa.company(),actors={OWNER:a.owner,OTHER:b.owner};for(const r of ['ADMIN','CASHIER','KITCHEN','ACCOUNTANT'])actors[r]=await qa.fixture(r,a.tenant);actors.PLATFORM_ADMIN=await qa.fixture('PLATFORM_ADMIN');
 const sessions={};const expect=async(call,status)=>{const r=await call;assert.equal(r.status,status,`HTTP ${r.status} expected ${status}: ${JSON.stringify(r.body)}`);return r.body;};
 for(const [r,u]of Object.entries(actors)){sessions[r]=await qa.session().init();await expect(sessions[r].login(u),200);}
 const anonymous=await qa.session().init();
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Recife'}).format(new Date()),month=today.slice(0,7);
 const company={cnpj:qa.documentNumber(),legalName:'Usability Company',tradeName:'Usability',corporateEmail:`business-${qa.run}@empresa.com.br`,phone:'11999999999'},password=randomBytes(24).toString('hex'),owner={name:'Usability Owner',email:`new-${qa.run}@gmail.com`,password,passwordConfirmation:password};
 for(const phone of ['123','119999999999','119abcd9999'])await check(`HTTP backend rejects phone ${phone}`,()=>expect(anonymous.api('post','/auth/onboarding',{company:{...company,phone},owner}),400));
 for(const corporateEmail of ['user@gmail','user@','user@@empresa.com'])await check(`HTTP backend rejects email ${corporateEmail}`,()=>expect(anonymous.api('post','/auth/onboarding',{company:{...company,corporateEmail},owner}),400));
 await check('HTTP confirmation mismatch is clear Portuguese',async()=>{const r=await expect(anonymous.api('post','/auth/onboarding',{company,owner:{...owner,passwordConfirmation:'DifferentSecure123!'}}),400);assert.ok(JSON.stringify(r).includes('As senhas informadas não são iguais.'));});
 await check('HTTP owner profile uses session and hides secrets',async()=>{const p=await expect(sessions.OWNER.api('get','/users/me/profile'),200);assert.equal(p.email,actors.OWNER.email);assert.equal(p.company.legalName,a.tenant.legalName);assert.match(p.company.cnpjMasked,/^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/);for(const k of ['passwordHash','cpfEncrypted','cpfHash','sessionVersion'])assert.ok(!JSON.stringify(p).includes(k));});
 await check('HTTP owner self role/status/profile denied and audited',async()=>{guard();const before=await qa.db.collection('users_v2').findOne({_id:a.tenant.ownerId});await expect(sessions.OWNER.api('patch',`/users/${actors.OWNER.id}/role`,{role:'CASHIER'}),403);await expect(sessions.OWNER.api('patch',`/users/${actors.OWNER.id}/status`,{status:'INACTIVE'}),403);await expect(sessions.OWNER.api('patch','/users/me/profile',{name:'Bypass',tenantId:b.owner.tenantId}),403);assert.deepEqual(await qa.db.collection('users_v2').findOne({_id:a.tenant.ownerId}),before);assert.ok(await qa.db.collection('security_audit_events_v2').countDocuments({tenantId:a.tenant._id,action:'profile.update',outcome:'denied'}) || await qa.db.collection('security_audit_events_v2').countDocuments({tenantId:a.tenant._id,action:'profile.update'}));});
 await check('HTTP platform profile is global without tenant commercial data',async()=>{const p=await expect(sessions.PLATFORM_ADMIN.api('get','/users/me/profile'),200);assert.equal(p.company,null);assert.equal(p.tenantId,null);});
 const cost=await expect(sessions.OWNER.api('post','/finance/categories',{name:'Insumos',type:'CUSTO_PRODUCAO'}),201),expense=await expect(sessions.OWNER.api('post','/finance/categories',{name:'Insumos',type:'DESPESA_OPERACIONAL'}),201);
 const entryBody={description:'Frango',categoryId:cost._id,type:'CUSTO_PRODUCAO',nature:'VARIAVEL',expectedAmountCents:3500,competence:month,competenceDate:today,purchaseDate:today,entryKind:'INPUT_PURCHASE',quantity:2,unit:'KG'};
 let paid,pending;
 await check('HTTP Frango in Insumos purchased and paid today, no future due date',async()=>{paid=await expect(sessions.OWNER.api('post','/finance/entries',{...entryBody,initialPayment:{paidAmountCents:3500,paidOn:today,origin:'PJ',method:'PIX'}}),201);assert.equal(paid.status,'PAGO');assert.equal(paid.dueDate,today);assert.equal(paid.description,'Frango');assert.equal(paid.payment.paidOn,today);const h=await expect(sessions.OWNER.api('get',`/finance/entries/${paid._id}/history`),200);assert.equal(h.items[0].after.status,'PAGO');});
 await check('HTTP pending cost and pending operational expense',async()=>{pending=await expect(sessions.OWNER.api('post','/finance/entries',entryBody),201);assert.equal(pending.status,'PENDENTE');const e=await expect(sessions.OWNER.api('post','/finance/entries',{...entryBody,categoryId:expense._id,type:'DESPESA_OPERACIONAL'}),201);assert.equal(e.status,'PENDENTE');});
 for(const patch of [{purchaseDate:'2026-02-30'},{expectedAmountCents:-1},{quantity:0},{quantity:1,unit:undefined},{competenceDate:'2020-01-01'},{tenantId:b.owner.tenantId}])await check(`HTTP invalid purchase ${Object.keys(patch).join(',')}`,()=>expect(sessions.OWNER.api('post','/finance/entries',{...entryBody,...patch}),400));
 await check('HTTP purchase filters and cross-tenant isolation',async()=>{const rows=await expect(sessions.ACCOUNTANT.api('get','/finance/entries?entryKind=INPUT_PURCHASE&description=Frango'),200);assert.ok(rows.total>=3);await expect(sessions.OTHER.api('get',`/finance/entries/${paid._id}`),404);});
 const fileRequest=async(session,id,name,mime,bytes)=>{guard();const body=new FormData();body.append('file',new Blob([bytes],{type:mime}),name);const res=await fetch(`${qa.baseURL}/api/finance/entries/${id}/attachments`,{method:'POST',headers:{Origin:qa.baseURL,Cookie:[...session.cookies].map(([k,v])=>`${k}=${v}`).join('; '),'X-CSRF-Token':session.cookies.get('salgados_csrf')},body});return {status:res.status,body:await res.json()};};
 const xml=Buffer.from('<?xml version="1.0"?><nfe><item>Frango</item></nfe>'),pdf=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF'),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jvRkAAAAASUVORK5CYII=','base64');
 const attachments=[];
 for(const [name,mime,bytes]of [['danfe.pdf','application/pdf',pdf],['nota.xml','application/xml',xml],['foto.png','image/png',png]])await check(`HTTP upload real ${name}`,async()=>{assert.equal(qa.transactions,true,'Replica set required');const row=await expect(fileRequest(sessions.OWNER,paid._id,name,mime,bytes),201);attachments.push(row);assert.ok(!JSON.stringify(row).includes('storageKey'));});
 await check('HTTP upload rejects false extension/content',()=>expect(fileRequest(sessions.OWNER,paid._id,'script.pdf','application/pdf',Buffer.from('<script>alert(1)</script>')),400));
 await check('HTTP upload rejects large file',()=>expect(fileRequest(sessions.OWNER,paid._id,'large.pdf','application/pdf',Buffer.alloc(5*1024*1024+1)),413));
 await check('HTTP upload rejects XML external entity',()=>expect(fileRequest(sessions.OWNER,paid._id,'nota.xml','application/xml',Buffer.from('<!DOCTYPE a [<!ENTITY e SYSTEM "file:///secret">]><a>&e;</a>')),400));
 await check('HTTP attachment cross-tenant read/write denied',async()=>{await expect(fileRequest(sessions.OTHER,paid._id,'nota.xml','application/xml',xml),404);await expect(sessions.OTHER.api('get',`/finance/entries/${paid._id}/attachments`),404);await expect(sessions.OTHER.api('get',`/finance/entries/${paid._id}/attachments/${attachments[0]._id}/download`),404);await expect(sessions.OTHER.api('post',`/finance/entries/${paid._id}/attachments/${attachments[0]._id}/remove`,{}),404);});
 await check('HTTP private download and logical removal',async()=>{const cookie=[...sessions.OWNER.cookies].map(([k,v])=>`${k}=${v}`).join('; '),url=`${qa.baseURL}/api/finance/entries/${paid._id}/attachments/${attachments[0]._id}/download`;const r=await fetch(url,{headers:{Origin:qa.baseURL,Cookie:cookie}});assert.equal(r.status,200);assert.ok(r.headers.get('content-disposition').startsWith('attachment'));assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.equal(Buffer.from(await r.arrayBuffer()).compare(pdf),0);await expect(sessions.OWNER.api('post',`/finance/entries/${paid._id}/attachments/${attachments[0]._id}/remove`,{}),201);await expect(sessions.OWNER.api('get',`/finance/entries/${paid._id}/attachments/${attachments[0]._id}/download`),404);});
 await check('HTTP concurrent uploads obey quantity limit',async()=>{const results=await Promise.all(Array.from({length:4},(_,i)=>fileRequest(sessions.OWNER,paid._id,`extra${i}.xml`,'application/xml',xml)));assert.equal(results.filter(r=>r.status===201).length,3);assert.equal(results.filter(r=>r.status===409).length,1);assert.equal((await expect(sessions.OWNER.api('get',`/finance/entries/${paid._id}/attachments`),200)).length,5);});
 let produced,bought;
 await check('HTTP product origin and sales group required',()=>expect(sessions.OWNER.api('post','/products',{name:'Unknown',category:'Other',priceCents:100}),400));
 await check('HTTP produced snack and purchased beverage',async()=>{produced=await expect(sessions.OWNER.api('post','/products',{name:'Coxinha usability',category:'Salgados',priceCents:500,origin:'PRODUCED',salesGroup:'SNACKS'}),201);bought=await expect(sessions.OWNER.api('post','/products',{name:'Refrigerante usability',category:'Bebidas',priceCents:600,origin:'PURCHASED_FOR_RESALE',salesGroup:'BEVERAGES'}),201);});
 await check('HTTP kitchen only produced; beverage rejected directly',async()=>{const catalog=await expect(sessions.KITCHEN.api('get','/products'),200);assert.ok(catalog.some(p=>p._id===produced._id));assert.ok(!catalog.some(p=>p._id===bought._id));await expect(sessions.KITCHEN.api('post','/productions',{productId:bought._id,quantity:2}),400);await expect(sessions.KITCHEN.api('post','/productions',{productId:produced._id,quantity:10}),201);});
 await check('HTTP purchased stock entry is atomic and scoped',async()=>{await expect(sessions.OTHER.api('post',`/products/${bought._id}/purchases`,{quantity:20}),404);await expect(sessions.OWNER.api('post',`/products/${produced._id}/purchases`,{quantity:20}),400);assert.equal((await expect(sessions.OWNER.api('post',`/products/${bought._id}/purchases`,{quantity:20}),201)).availableStock,20);await expect(sessions.CASHIER.api('post',`/products/${bought._id}/purchases`,{quantity:20}),403);});
 let sale;
 await check('HTTP sale reserves stock, payment preserves stock and snapshot groups',async()=>{sale=await expect(sessions.CASHIER.api('post','/orders',{type:'TAKEAWAY',items:[{productId:produced._id,quantity:2},{productId:bought._id,quantity:1}]}),201);assert.deepEqual(sale.items.map(i=>i.salesGroup).sort(),['BEVERAGES','SNACKS']);await expect(sessions.CASHIER.api('post',`/orders/${sale._id}/finalize`,{payments:[{method:'PIX',amountCents:1600}]}),201);const catalog=await expect(sessions.OWNER.api('get','/products'),200);assert.equal(catalog.find(p=>p._id===produced._id).availableStock,8);assert.equal(catalog.find(p=>p._id===bought._id).availableStock,19);});
 await check('HTTP accountant fiscal filters, pagination and detail',async()=>{const r=await expect(sessions.ACCOUNTANT.api('get',`/finance/sales?date=${today}&status=FINALIZED&salesGroup=BEVERAGES&productId=${bought._id}&method=PIX&number=${sale.number}&cashierId=${actors.CASHIER.id}&sort=number&direction=asc&limit=1`),200);assert.equal(r.total,1);assert.equal(r.items[0].company.cnpj,a.tenant.cnpj);assert.equal(r.items[0].fiscalStatus,'NOT_INTEGRATED');const d=await expect(sessions.ACCOUNTANT.api('get',`/finance/sales/${sale._id}`),200);assert.equal(d.items.length,2);assert.equal((await expect(sessions.ACCOUNTANT.api('get','/finance/sales?limit=1&page=2'),200)).items.length,0);});
 await check('HTTP accountant fiscal read-only and tenant isolation',async()=>{await expect(sessions.OTHER.api('get',`/finance/sales/${sale._id}`),404);assert.equal((await expect(sessions.OTHER.api('get','/finance/sales'),200)).total,0);await expect(sessions.ACCOUNTANT.api('post',`/orders/${sale._id}/cancel`,{reason:'Not allowed'}),403);await expect(sessions.ACCOUNTANT.api('patch',`/finance/sales/${sale._id}`,{status:'CANCELED'}),404);});
 for(const role of ['CASHIER','KITCHEN','PLATFORM_ADMIN'])await check(`HTTP ${role} denied fiscal sales`,async()=>{for(const path of ['/finance/sales','/finance/sales-export',`/finance/sales/${sale._id}`])await expect(sessions[role].api('get',path),403);});
 await check('HTTP CSV export and date/ObjectId validations',async()=>{const r=await fetch(`${qa.baseURL}/api/finance/sales-export`,{headers:{Origin:qa.baseURL,Cookie:[...sessions.ACCOUNTANT.cookies].map(([k,v])=>`${k}=${v}`).join('; ')}});assert.equal(r.status,200);const csv=await r.text();assert.ok(csv.includes('Refrigerante usability'));assert.ok(csv.includes(a.tenant.cnpj));await expect(sessions.ACCOUNTANT.api('get','/finance/sales?date=2026-02-30'),400);await expect(sessions.ACCOUNTANT.api('get','/finance/sales?cashierId=invalid'),400);});
 if(browserEnabled){const {usabilityBrowser}=await import('./usability-browser.mjs');await usabilityBrowser(qa,{actors,a,bought,produced,paid},check);}
 await check('bundle excludes generated secrets and database URIs',async()=>{const dir=fileURLToPath(new URL('../apps/web/dist/web/browser/',import.meta.url));let count=0;for(const name of await readdir(dir)){if(!name.endsWith('.js'))continue;const text=await readFile(dir+name,'utf8');for(const secret of [process.env.JWT_SECRET,process.env.CPF_ENCRYPTION_KEY,process.env.CPF_HASH_KEY,...Object.values(actors).map(u=>u.password)])assert.ok(!text.includes(secret));assert.ok(!/mongodb(?:\+srv)?:\/\//.test(text));count++;}assert.ok(count>5);console.log(`BUNDLE_SCAN ${count} files, zero findings`);});
}
