import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { ClientSession } from 'mongoose';
import type { AuthUser } from '../common/auth-user.js';
import { OperationalStore } from '../common/operational-store.js';
import { EntitlementsService } from '../commerce/entitlements.service.js';
import { civilDate } from '../contracts/contracts.rules.js';
import { BUSINESS_MODELS } from '../business/business.schemas.js';
import { PURCHASE_MODELS } from './purchases.schemas.js';
import * as D from './purchases.dto.js';
const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
@Injectable()
export class PurchasesService {
 constructor(private store:OperationalStore,private entitlements:EntitlementsService){}
 private model(name:string){return this.store.model(name);}
 private clean(row:any){const {inputHash,requestId,...r}=row.toObject?row.toObject():row;return r;}
 private date(value:string){try{return civilDate(value);}catch{throw new BadRequestException('Data civil inválida.');}}
 private write<T>(u:AuthUser,p:string,event:string,fn:(a:AuthUser,s:ClientSession)=>Promise<T>){return this.store.write(u,p,event,[...PURCHASE_MODELS,...BUSINESS_MODELS.filter(m=>m.name==='CashEntry')],fn);}
 private async order(a:AuthUser,id:string,s?:ClientSession){const p=await this.model('PurchaseOrder').findOne({_id:this.store.id(id),tenantId:a.tenantId}).session(s??null);if(!p)throw new NotFoundException('Pedido de compra não encontrado.');return p;}
 async catalog(u:AuthUser,q:D.PurchaseQuery,kind:'products'|'suppliers'){const a=await this.store.access.require(u,['compras.visualizar']);return this.store.page(kind==='products'?'Product':'BusinessParty',{tenantId:a.tenantId,active:true,...(kind==='suppliers'?{roles:'SUPPLIER'}:{}),...(q.search?{name:new RegExp(escape(q.search),'i')}:{})},q,{name:1,_id:1},'_id name unit');}
 async list(u:AuthUser,q:D.PurchaseQuery){const a=await this.store.access.require(u,['compras.visualizar']);return this.store.page('PurchaseOrder',{tenantId:a.tenantId,...(q.status?{status:q.status}:{}),...(q.search?{$or:['reference','supplierName'].map(k=>({[k]:new RegExp(escape(q.search!),'i')}))}:{})},q);}
 async detail(u:AuthUser,id:string){const a=await this.store.access.require(u,['compras.visualizar']);return this.clean(await this.order(a,id));}
 async receipts(u:AuthUser,q:D.PurchaseQuery){const a=await this.store.access.require(u,['compras.visualizar']);if(!q.orderId)throw new BadRequestException('Selecione o pedido.');await this.order(a,q.orderId);return this.store.page('PurchaseReceipt',{tenantId:a.tenantId,orderId:q.orderId},q);}
 async create(u:AuthUser,d:D.PurchaseDto){this.date(d.expectedOn);if(new Set(d.lines.map(l=>l.productId)).size!==d.lines.length)throw new BadRequestException('Não repita produtos.');return this.write(u,'compras.criar','purchases.created',async(a,s)=>{
  const previous=await this.store.replay('PurchaseOrder',a,d,s);if(previous)return this.clean(previous);if(await this.model('PurchaseOrder').exists({tenantId:a.tenantId,reference:d.reference.trim()}).session(s))throw new ConflictException('Referência de pedido já utilizada.');
  const supplier=await this.model('BusinessParty').findOne({_id:d.supplierId,tenantId:a.tenantId,roles:'SUPPLIER',active:true}).session(s);if(!supplier)throw new BadRequestException('Fornecedor indisponível.');
  const lines=[];let totalCents=0;for(const item of d.lines){const product=await this.model('Product').findOne({_id:item.productId,tenantId:a.tenantId,active:true}).session(s);if(!product)throw new BadRequestException('Produto indisponível.');const total=item.quantity*item.unitCents;totalCents+=total;if(!Number.isSafeInteger(totalCents)||totalCents>1e12)throw new BadRequestException('Valor do pedido excede o limite.');lines.push({...item,productName:product.name,unit:product.unit,totalCents:total});}
  const [order]=await this.model('PurchaseOrder').create([{...d,...this.store.fields(a,d),supplierName:supplier.name,lines,totalCents,history:[{status:'DRAFT',reason:'Pedido criado',actorId:a.sub,at:new Date()}]}],{session:s});return this.clean(order);
 });}
 async state(u:AuthUser,id:string,d:D.PurchaseStateDto){return this.write(u,d.status==='APPROVED'?'compras.aprovar':'compras.cancelar','purchases.status.changed',async(a,s)=>{const order=await this.order(a,id,s);if(order.version!==d.version)throw new ConflictException('Pedido atualizado. Recarregue.');const transitions:Record<string,string[]>={DRAFT:['APPROVED','CANCELED'],APPROVED:['CANCELED'],PARTIAL:['CLOSED']};if(!transitions[order.status]?.includes(d.status))throw new ConflictException('Transição inválida. Pedido parcialmente recebido só pode encerrar o saldo pendente.');order.status=d.status;order.version++;order.history.push({status:d.status,reason:d.reason,actorId:a.sub,at:new Date()});await order.save({session:s});return this.clean(order);});}
 async receive(u:AuthUser,id:string,d:D.PurchaseReceiptDto){this.date(d.receivedOn);if(d.receivedOn>new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'}))throw new BadRequestException('Recebimento não pode estar no futuro.');if(new Set(d.lines.map(l=>l.productId)).size!==d.lines.length)throw new BadRequestException('Não repita produtos.');if(!!d.accountId!==!!d.dueDate)throw new BadRequestException('Informe conta e vencimento juntos.');if(d.dueDate)this.date(d.dueDate);return this.write(u,'compras.receber','purchases.received',async(a,s)=>{
  const order=await this.order(a,id,s),payload={...d,orderId:id};const previous=await this.store.replay('PurchaseReceipt',a,payload,s);if(previous)return this.clean(previous);if(!['APPROVED','PARTIAL'].includes(order.status))throw new ConflictException('Pedido não permite recebimento.');if(await this.model('PurchaseReceipt').exists({tenantId:a.tenantId,reference:d.reference.trim()}).session(s))throw new ConflictException('Documento de recebimento já registrado.');
  const stockApplied=await this.entitlements.has(a.tenantId!,'INVENTORY',s);const receiptId=new this.store.db.base.Types.ObjectId(),lines=[];let totalCents=0;
  for(const received of d.lines){const line=order.lines.find((l:any)=>String(l.productId)===received.productId);if(!line||received.quantity>line.quantity-line.receivedQuantity)throw new BadRequestException('Quantidade excede o saldo pendente do pedido.');const cost=received.quantity*line.unitCents;totalCents+=cost;line.receivedQuantity+=received.quantity;lines.push({productId:line.productId,productName:line.productName,unit:line.unit,quantity:received.quantity,unitCents:line.unitCents,totalCents:cost});
   if(stockApplied){const product=await this.model('Product').findOneAndUpdate({_id:line.productId,tenantId:a.tenantId,active:true,availableStock:{$lte:1000000-received.quantity}},{$inc:{availableStock:received.quantity,version:1}},{session:s,returnDocument:'after'});if(!product)throw new ConflictException('Produto indisponível ou limite de estoque excedido.');await this.model('StockMovement').create([{tenantId:a.tenantId,productId:line.productId,productName:line.productName,quantityChange:received.quantity,type:'PURCHASE',referenceId:String(receiptId),userId:a.sub,userName:a.name}],{session:s});}
  }
  let entryId:any;if(d.accountId){await this.store.access.require(a,['tesouraria.criar'],s);if(!await this.model('CashAccount').exists({_id:d.accountId,tenantId:a.tenantId,active:true}).session(s))throw new BadRequestException('Conta financeira indisponível.');if(totalCents<1)throw new BadRequestException('Recebimento sem valor não gera obrigação financeira.');const [entry]=await this.model('CashEntry').create([{tenantId:a.tenantId,actorId:a.sub,accountId:d.accountId,partyId:order.supplierId,description:`Compra ${order.reference}`,direction:'OUT',amountCents:totalCents,dueDate:d.dueDate,reference:`purchase:${receiptId}`,status:'PENDING'}],{session:s});entryId=entry._id;}
  const [receipt]=await this.model('PurchaseReceipt').create([{...this.store.fields(a,payload),_id:receiptId,orderId:order._id,reference:d.reference,receivedOn:d.receivedOn,assessment:d.assessment,lines,totalCents,stockApplied,entryId}],{session:s});order.status=order.lines.every((l:any)=>l.receivedQuantity===l.quantity)?'RECEIVED':'PARTIAL';order.version++;order.history.push({status:order.status,reason:`Recebimento ${d.reference}`,actorId:a.sub,at:new Date()});await order.save({session:s});return this.clean(receipt);
 });}
}
