import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { ClientSession } from 'mongoose';
import type { AuthUser } from '../common/auth-user.js';
import { OperationalStore } from '../common/operational-store.js';
import { LOGISTICS_MODELS } from './logistics.schemas.js';
import * as D from './logistics.dto.js';
const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
@Injectable()
export class LogisticsService {
 constructor(private store:OperationalStore){}
 private model(name:string){return this.store.model(name);}
 private clean(row:any){const {inputHash,requestId,...r}=row.toObject?row.toObject():row;return r;}
 private write<T>(u:AuthUser,p:string,event:string,fn:(a:AuthUser,s:ClientSession)=>Promise<T>){return this.store.write(u,p,event,LOGISTICS_MODELS,fn);}
 private scope(a:AuthUser){return {tenantId:a.tenantId,...(a.permissions?.includes('logistica.planejar')?{}:{assignedId:a.sub})};}
 private async shipment(a:AuthUser,id:string,s?:ClientSession){const r=await this.model('DeliveryShipment').findOne({_id:this.store.id(id),...this.scope(a)}).session(s??null);if(!r)throw new NotFoundException('Remessa não encontrada.');return r;}
 private async driver(a:AuthUser,id:string,s:ClientSession){const r=await this.model('User').findOne({_id:id,tenantId:a.tenantId,status:'ACTIVE',active:true}).select('name').session(s);if(!r)throw new BadRequestException('Entregador indisponível.');return r;}
 async people(u:AuthUser,q:D.LogisticsQuery){const a=await this.store.access.require(u,['logistica.planejar']);return this.store.page('User',{tenantId:a.tenantId,status:'ACTIVE',active:true},q,{name:1,_id:1},'_id name');}
 async orders(u:AuthUser,q:D.LogisticsQuery){const a=await this.store.access.require(u,['logistica.planejar']);return this.store.page('DeliveryOrder',{tenantId:a.tenantId,...(q.search?{$or:['reference','recipient'].map(k=>({[k]:new RegExp(escape(q.search!),'i')}))}:{})},q);}
 async shipments(u:AuthUser,q:D.LogisticsQuery){const a=await this.store.access.require(u,['logistica.visualizar']);return this.store.page('DeliveryShipment',{...this.scope(a),...(q.orderId?{orderId:q.orderId}:{}),...(q.status?{status:q.status}:{}),...(q.search?{$or:['reference','recipient','routeName'].map(k=>({[k]:new RegExp(escape(q.search!),'i')}))}:{})},q,{windowStart:1,routeName:1,stopNumber:1,_id:1});}
 async detail(u:AuthUser,id:string){const a=await this.store.access.require(u,['logistica.visualizar']);return this.clean(await this.shipment(a,id));}
 async createOrder(u:AuthUser,d:D.DeliveryOrderDto){if(![d.windowStart,d.windowEnd].every(v=>/(Z|[+-]\d{2}:\d{2})$/.test(v))||new Date(d.windowEnd)<=new Date(d.windowStart))throw new BadRequestException('Janela de entrega inválida; informe o fuso.');if(new Set(d.lines.map(l=>l.code.trim())).size!==d.lines.length)throw new BadRequestException('Código de item repetido.');return this.write(u,'logistica.planejar','logistics.order.created',async(a,s)=>{
  const previous=await this.store.replay('DeliveryOrder',a,d,s);if(previous)return this.clean(previous);if(await this.model('DeliveryOrder').exists({tenantId:a.tenantId,reference:d.reference.trim()}).session(s))throw new ConflictException('Origem já registrada.');if(d.partyId&&!await this.model('BusinessParty').exists({_id:d.partyId,tenantId:a.tenantId,active:true}).session(s))throw new BadRequestException('Contato indisponível.');
  const lines=[];for(const l of d.lines){let description=l.description;if(l.productId){const product=await this.model('Product').findOne({_id:l.productId,tenantId:a.tenantId,active:true}).session(s);if(!product)throw new BadRequestException('Produto indisponível.');description=product.name;}lines.push({...l,description});}
  const [r]=await this.model('DeliveryOrder').create([{...d,...this.store.fields(a,d),lines}],{session:s});return this.clean(r);
 });}
 async createShipment(u:AuthUser,d:D.ShipmentDto){if(new Set(d.lines.map(l=>l.code.trim())).size!==d.lines.length)throw new BadRequestException('Código de item repetido.');return this.write(u,'logistica.planejar','logistics.shipment.created',async(a,s)=>{
  const previous=await this.store.replay('DeliveryShipment',a,d,s);if(previous)return this.clean(previous);const order=await this.model('DeliveryOrder').findOne({_id:d.orderId,tenantId:a.tenantId}).session(s);if(!order)throw new NotFoundException('Ordem não encontrada.');const driver=await this.driver(a,d.assignedId,s);const lines=[];for(const item of d.lines){const l=order.lines.find((l:any)=>l.code===item.code.trim());if(!l||item.quantity>l.quantity-l.allocated)throw new ConflictException('Quantidade já destinada a outra remessa.');l.allocated+=item.quantity;lines.push({code:l.code,productId:l.productId,description:l.description,quantity:item.quantity});}
  order.version++;await order.save({session:s});const [r]=await this.model('DeliveryShipment').create([{...d,...this.store.fields(a,d),reference:order.reference,recipient:order.recipient,phone:order.phone,address:order.address,windowStart:order.windowStart,windowEnd:order.windowEnd,notes:order.notes,assignedName:driver.name,lines,history:[{status:'PENDING',reason:'Remessa planejada',actorId:a.sub,at:new Date()}]}],{session:s});return this.clean(r);
 });}
 async assign(u:AuthUser,id:string,d:D.ShipmentAssignDto){return this.write(u,'logistica.planejar','logistics.shipment.assigned',async(a,s)=>{const r=await this.shipment(a,id,s);if(r.version!==d.version||['DELIVERED','RETURN_RECEIVED','CANCELED'].includes(r.status))throw new ConflictException('Remessa alterada ou encerrada.');const driver=await this.driver(a,d.assignedId,s);r.assignedId=d.assignedId;r.assignedName=driver.name;r.routeName=d.routeName;r.stopNumber=d.stopNumber;r.version++;r.history.push({status:r.status,reason:`Reatribuição: ${d.reason}`,actorId:a.sub,at:new Date()});await r.save({session:s});return this.clean(r);});}
 async state(u:AuthUser,id:string,d:D.ShipmentStateDto){const permission=['IN_TRANSIT','DELIVERED','FAILED'].includes(d.status)?'logistica.executar':d.status==='CHECKED'?'logistica.conferir':d.status==='DISPATCHED'?'logistica.despachar':'logistica.planejar';return this.write(u,permission,'logistics.shipment.changed',async(a,s)=>{
  const r=await this.shipment(a,id,s);if(r.version!==d.version)throw new ConflictException('Remessa atualizada.');const transitions:Record<string,string[]>={PENDING:['CHECKED','CANCELED'],CHECKED:['DISPATCHED','CANCELED'],DISPATCHED:['IN_TRANSIT'],IN_TRANSIT:['DELIVERED','FAILED'],FAILED:['IN_TRANSIT','RETURN_RECEIVED']};if(!transitions[r.status]?.includes(d.status))throw new ConflictException('Transição de entrega inválida.');if(d.status==='DELIVERED'&&!d.receivedBy?.trim())throw new BadRequestException('Informe quem recebeu.');
  if(d.status==='CANCELED'){const order=await this.model('DeliveryOrder').findOne({_id:r.orderId,tenantId:a.tenantId}).session(s);if(!order)throw new ConflictException('Origem ausente.');for(const line of r.lines){const original=order.lines.find((l:any)=>l.code===line.code);if(!original||original.allocated<line.quantity)throw new ConflictException('Saldo de remessas inconsistente.');original.allocated-=line.quantity;}order.version++;await order.save({session:s});}
  r.status=d.status;r.version++;if(d.status==='DELIVERED'){r.receivedBy=d.receivedBy;r.deliveredAt=new Date();}r.history.push({status:d.status,reason:d.reason,actorId:a.sub,at:new Date()});await r.save({session:s});return this.clean(r);
 });}
}
