import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import type { ClientSession } from 'mongoose';
import type { AuthUser } from '../common/auth-user.js';
import { OperationalStore } from '../common/operational-store.js';
import { LOYALTY_MODELS } from './loyalty.schemas.js';
import * as D from './loyalty.dto.js';
export function earnedPoints(cents:number,unit:number,cap:number){if(!Number.isSafeInteger(cents)||cents<1||cents>1e12||!Number.isSafeInteger(unit)||unit<1||!Number.isSafeInteger(cap)||cap<1)throw new Error('Regra de pontos inválida.');return Math.min(Math.floor(cents/unit),cap);}
const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
@Injectable()
export class LoyaltyService {
  constructor(private store:OperationalStore){}
  private model(name:string){return this.store.model(name);}
  private clean(row:any){const {inputHash,requestId,...r}=row.toObject?row.toObject():row;return r;}
  private write<T>(u:AuthUser,p:string,event:string,fn:(a:AuthUser,s:ClientSession)=>Promise<T>){return this.store.write(u,p,event,LOYALTY_MODELS,fn);}
  private async program(a:AuthUser,id:string,s?:ClientSession,active=false){const p=await this.model('LoyaltyProgram').findOne({_id:this.store.id(id),tenantId:a.tenantId,...(active?{active:true}:{})}).session(s??null);if(!p)throw new NotFoundException('Programa indisponível.');return p;}
  private async member(a:AuthUser,id:string,s?:ClientSession){const m=await this.model('LoyaltyMember').findOne({_id:this.store.id(id),tenantId:a.tenantId}).session(s??null);if(!m)throw new NotFoundException('Participante não encontrado.');return m;}
  async programs(u:AuthUser,q:D.LoyaltyQuery){const a=await this.store.access.require(u,['fidelidade.visualizar']);return this.store.page('LoyaltyProgram',{tenantId:a.tenantId,...(q.search?{name:new RegExp(escape(q.search),'i')}:{})},q);}
  async createProgram(u:AuthUser,d:D.ProgramDto){return this.write(u,'fidelidade.configurar','loyalty.program.created',async(a,s)=>{const previous=await this.store.replay('LoyaltyProgram',a,d,s);if(previous)return this.clean(previous);const [p]=await this.model('LoyaltyProgram').create([{...d,...this.store.fields(a,d)}],{session:s});return this.clean(p);});}
  async state(u:AuthUser,id:string,d:D.ProgramStateDto){return this.write(u,'fidelidade.configurar','loyalty.program.changed',async(a,s)=>{const p=await this.program(a,id,s);if(p.version!==d.version)throw new ConflictException('Programa atualizado. Recarregue.');p.active=d.active;p.version++;await p.save({session:s});return this.clean(p);});}
  async enroll(u:AuthUser,d:D.MemberDto){return this.write(u,'fidelidade.aderir','loyalty.member.enrolled',async(a,s)=>{const previous=await this.store.replay('LoyaltyMember',a,d,s);if(previous)return this.clean(previous);const p=await this.program(a,d.programId,s,true);const party=await this.model('BusinessParty').findOne({_id:d.partyId,tenantId:a.tenantId,active:true,roles:'CUSTOMER'}).session(s);if(!party)throw new BadRequestException('Cliente indisponível.');if(await this.model('LoyaltyMember').exists({tenantId:a.tenantId,programId:p._id,partyId:party._id}).session(s))throw new ConflictException('Cliente já participa deste programa.');const [m]=await this.model('LoyaltyMember').create([{...this.store.fields(a,d),programId:p._id,partyId:party._id,partyName:party.name,acceptedAt:new Date(),termsSnapshot:p.terms,marketingConsent:d.marketingConsent}],{session:s});return this.clean(m);});}
  async members(u:AuthUser,q:D.LoyaltyQuery){const a=await this.store.access.require(u,['fidelidade.visualizar']);const f:any={tenantId:a.tenantId};if(q.programId)f.programId=q.programId;if(q.search)f.partyName=new RegExp(escape(q.search),'i');return this.store.page('LoyaltyMember',f,q);}
  async detail(u:AuthUser,id:string){const a=await this.store.access.require(u,['fidelidade.visualizar']),m=await this.member(a,id);const stats=await this.model('LoyaltyEntry').aggregate([{$match:{tenantId:this.store.id(a.tenantId!),memberId:m._id,kind:'CREDIT'}},{$group:{_id:null,available:{$sum:{$cond:[{$gt:['$expiresAt',new Date()]},'$remainingPoints',0]}},expired:{$sum:{$cond:[{$lte:['$expiresAt',new Date()]},'$remainingPoints',0]}},issued:{$sum:'$points'}}}]);return {...this.clean(m),summary:stats[0]??{available:0,expired:0,issued:0},program:this.clean(await this.program(a,String(m.programId)))};}
  async entries(u:AuthUser,q:D.LoyaltyQuery){const a=await this.store.access.require(u,['fidelidade.visualizar']);if(!q.memberId)throw new BadRequestException('Informe o participante.');await this.member(a,q.memberId);return this.store.page('LoyaltyEntry',{tenantId:a.tenantId,memberId:q.memberId},q);}
  private async reference(a:AuthUser,programId:any,kind:string,reference:string,s:ClientSession){if(await this.model('LoyaltyEntry').exists({tenantId:a.tenantId,programId,kind,externalReference:reference.trim()}).session(s))throw new ConflictException('Origem já registrada neste programa.');}
  async earn(u:AuthUser,id:string,d:D.EarnDto){return this.write(u,'fidelidade.pontuar','loyalty.points.credited',async(a,s)=>{
    const m=await this.member(a,id,s),p=await this.program(a,String(m.programId),s,true);const payload={...d,memberId:id};const previous=await this.store.replay('LoyaltyEntry',a,payload,s);if(previous)return this.clean(previous);await this.reference(a,p._id,'CREDIT',d.externalReference,s);
    const points=earnedPoints(d.eligibleCents,p.spendCentsPerPoint,p.maxPointsPerOperation);if(!points)throw new BadRequestException('Valor abaixo do mínimo para um ponto.');const debtOffset=Math.min(points,m.debtPoints);m.debtPoints-=debtOffset;m.version++;await m.save({session:s});
    const [entry]=await this.model('LoyaltyEntry').create([{...this.store.fields(a,payload),programId:p._id,memberId:m._id,kind:'CREDIT',externalReference:d.externalReference,reason:d.reason,points,remainingPoints:points-debtOffset,debtOffset,eligibleCents:d.eligibleCents,expiresAt:new Date(Date.now()+p.validityDays*86400000),ruleSnapshot:{spendCentsPerPoint:p.spendCentsPerPoint,validityDays:p.validityDays,maxPointsPerOperation:p.maxPointsPerOperation}}],{session:s});return this.clean(entry);
  });}
  async redeem(u:AuthUser,id:string,d:D.RedeemDto){return this.write(u,'fidelidade.resgatar','loyalty.points.redeemed',async(a,s)=>{
    const m=await this.member(a,id,s),p=await this.program(a,String(m.programId),s,true);const payload={...d,memberId:id},previous=await this.store.replay('LoyaltyEntry',a,payload,s);if(previous)return this.clean(previous);await this.reference(a,p._id,'REDEEM',d.externalReference,s);if(m.debtPoints>0)throw new ConflictException('Pontos pendentes de compensação impedem o resgate.');
    const credits=await this.model('LoyaltyEntry').find({tenantId:a.tenantId,memberId:m._id,kind:'CREDIT',remainingPoints:{$gt:0},expiresAt:{$gt:new Date()}}).sort({expiresAt:1,_id:1}).session(s);if(credits.reduce((n,c)=>n+c.remainingPoints,0)<d.points)throw new ConflictException('Saldo de pontos insuficiente.');let remaining=d.points;const allocations=[];for(const c of credits){if(!remaining)break;const points=Math.min(remaining,c.remainingPoints);remaining-=points;c.remainingPoints-=points;c.version++;await c.save({session:s});allocations.push({entryId:c._id,points});}
    const [entry]=await this.model('LoyaltyEntry').create([{...this.store.fields(a,payload),programId:p._id,memberId:m._id,kind:'REDEEM',externalReference:d.externalReference,reason:d.reason,points:d.points,benefit:d.benefit,allocations}],{session:s});return this.clean(entry);
  });}
  async reverse(u:AuthUser,id:string,d:D.ReverseDto){return this.write(u,'fidelidade.estornar','loyalty.points.reversed',async(a,s)=>{
    const source=await this.model('LoyaltyEntry').findOne({_id:this.store.id(id),tenantId:a.tenantId,kind:'CREDIT'}).session(s);if(!source)throw new NotFoundException('Crédito não encontrado.');const payload={...d,sourceId:id},previous=await this.store.replay('LoyaltyEntry',a,payload,s);if(previous)return this.clean(previous);await this.reference(a,source.programId,'REVERSAL',d.externalReference,s);if(d.points>source.points-source.reversedPoints)throw new BadRequestException('Estorno supera os pontos ainda não estornados.');
    const remove=Math.min(source.remainingPoints,d.points),debtAdded=d.points-remove;source.remainingPoints-=remove;source.reversedPoints+=d.points;source.version++;await source.save({session:s});const member=await this.member(a,String(source.memberId),s);member.debtPoints+=debtAdded;member.version++;await member.save({session:s});
    const [entry]=await this.model('LoyaltyEntry').create([{...this.store.fields(a,payload),programId:source.programId,memberId:source.memberId,kind:'REVERSAL',sourceId:source._id,externalReference:d.externalReference,reason:d.reason,points:d.points,debtAdded}],{session:s});return this.clean(entry);
  });}
}
